export const PERMISSION_CATALOG = [
  ['dashboard:view', 'Visualizar dashboards', 'Dashboard', 'view'],
  ['dashboard:export', 'Exportar dashboards', 'Dashboard', 'export'],
  ['launches:view', 'Visualizar lançamentos', 'Lançamentos', 'view'],
  ['results:launch', 'Lancar resultados', 'Lançamentos', 'create'],
  ['results:approve', 'Aprovar resultados', 'Lançamentos', 'approve'],
  ['indicators:view', 'Visualizar indicadores', 'Indicadores', 'view'],
  ['indicators:create', 'Criar indicadores', 'Indicadores', 'create'],
  ['indicators:update', 'Editar indicadores', 'Indicadores', 'update'],
  ['indicators:delete', 'Excluir indicadores', 'Indicadores', 'delete'],
  ['actions:view', 'Visualizar planos de ação', 'Planos de ação', 'view'],
  ['actions:create', 'Criar planos de ação', 'Planos de ação', 'create'],
  ['actions:update', 'Editar planos de ação', 'Planos de ação', 'update'],
  ['actions:delete', 'Cancelar ou excluir logicamente planos', 'Planos de ação', 'delete'],
  ['actions:complete', 'Concluir planos de ação', 'Planos de ação', 'complete'],
  ['actions:effectiveness', 'Validar eficacia de planos de ação', 'Planos de ação', 'approve'],
  ['actions:reopen', 'Reabrir planos de ação', 'Planos de ação', 'update'],
  ['actions:extension:approve', 'Aprovar prorrogacao de prazo', 'Planos de ação', 'approve'],
  ['actions:analysis', 'Usar ferramentas de análise de causa', 'Planos de ação', 'manage'],
  ['actions:ai', 'Usar IA assistente em planos de ação', 'Planos de ação', 'assist'],
  ['actions:export', 'Exportar planos de ação', 'Planos de ação', 'export'],
  ['actions:view_all', 'Visualizar planos de outras areas', 'Planos de ação', 'view'],
  ['actions:manage_all', 'Gerenciar planos de toda empresa', 'Planos de ação', 'manage'],
  ['actions:manage', 'Gerenciar planos de ação', 'Planos de ação', 'manage'],
  ['actions:approve', 'Aprovar planos de ação', 'Planos de ação', 'approve'],
  ['deviations:view', 'Visualizar desvios e análises', 'Desvios', 'view'],
  ['deviations:manage', 'Gerenciar desvios e análises', 'Desvios', 'manage'],
  ['projects:view', 'Visualizar projetos', 'Projetos', 'view'],
  ['projects:manage', 'Gerenciar projetos', 'Projetos', 'manage'],
  ['meetings:view', 'Visualizar reuniões', 'Reuniões', 'view'],
  ['meetings:manage', 'Gerenciar reuniões', 'Reuniões', 'manage'],
  ['strategy:view', 'Visualizar mapa estratégico', 'Estratégia', 'view'],
  ['strategy:manage', 'Gerenciar mapa estratégico', 'Estratégia', 'manage'],
  ['strategy:maps:create', 'Criar mapas estratégicos', 'Estratégia', 'create'],
  ['strategy:maps:update', 'Editar mapas estratégicos', 'Estratégia', 'update'],
  ['strategy:maps:delete', 'Inativar mapas estratégicos', 'Estratégia', 'delete'],
  ['strategy:perspectives:create', 'Criar perspectivas estratégicas', 'Estratégia', 'create'],
  ['strategy:perspectives:update', 'Editar e reordenar perspectivas', 'Estratégia', 'update'],
  ['strategy:perspectives:delete', 'Inativar perspectivas estratégicas', 'Estratégia', 'delete'],
  ['strategy:objectives:create', 'Criar objetivos estratégicos', 'Estratégia', 'create'],
  ['strategy:objectives:update', 'Editar, mover e reordenar objetivos estratégicos', 'Estratégia', 'update'],
  ['strategy:objectives:delete', 'Inativar objetivos estratégicos', 'Estratégia', 'delete'],
  ['strategy:indicators:link', 'Vincular indicadores a objetivos estratégicos', 'Estratégia', 'link'],
  ['strategy:links:manage', 'Gerenciar ligacoes entre objetivos estratégicos', 'Estratégia', 'manage'],
  ['strategy:publish', 'Publicar versões do mapa estratégico', 'Estratégia', 'publish'],
  ['strategy:history:view', 'Visualizar histórico do mapa estratégico', 'Estratégia', 'view'],
  ['okrs:view', 'Visualizar OKRs', 'OKRs', 'view'],
  ['okrs:manage', 'Gerenciar OKRs', 'OKRs', 'manage'],
  ['org:view', 'Visualizar estrutura organizacional', 'Estrutura', 'view'],
  ['org:manage', 'Gerenciar estrutura organizacional', 'Estrutura', 'manage'],
  ['reports:export', 'Exportar relatorios', 'Relatorios', 'export'],
  ['settings:view', 'Visualizar configurações', 'Configurações', 'view'],
  ['settings:manage', 'Gerenciar parametros do sistema', 'Configurações', 'manage'],
  ['users:manage', 'Gerenciar usuários e permissões', 'Usuários', 'manage'],
  ['audit:view', 'Visualizar auditoria', 'Auditoria', 'view'],
  ['audit:export', 'Exportar auditoria', 'Auditoria', 'export'],
] as const;

export const DEFAULT_PROFILES = [
  {
    code: 'SUPER_ADMIN',
    name: 'Super Admin',
    role: 'SUPER_ADMIN',
    description: 'Acesso total ao sistema, seguranca, auditoria e parametros.',
    permissions: PERMISSION_CATALOG.map(([key]) => key),
  },
  {
    code: 'ADMIN',
    name: 'Admin',
    role: 'COMPANY_ADMIN',
    description: 'Administracao da empresa com acesso a usuários, estrutura e parametrizacao.',
    permissions: PERMISSION_CATALOG.map(([key]) => key).filter((key) => key !== 'audit:export'),
  },
  {
    code: 'GESTOR',
    name: 'Gestor',
    role: 'MANAGER',
    description: 'Gestão de indicadores, planos de ação e acompanhamentos do setor.',
    permissions: [
      'dashboard:view',
      'launches:view',
      'results:launch',
      'indicators:view',
      'indicators:create',
      'indicators:update',
      'actions:view',
      'actions:manage',
      'deviations:view',
      'deviations:manage',
      'meetings:view',
      'meetings:manage',
      'strategy:view',
      'reports:export',
      'org:view',
    ],
  },
  {
    code: 'USUARIO',
    name: 'Usuário',
    role: 'COLLABORATOR',
    description: 'Acesso operacional para lançamentos e execucao de atividades.',
    permissions: ['dashboard:view', 'launches:view', 'results:launch', 'indicators:view', 'actions:view', 'actions:manage', 'meetings:view'],
  },
  {
    code: 'VISUALIZADOR',
    name: 'Visualizador',
    role: 'VIEWER',
    description: 'Acesso somente leitura aos principais paineis e relatorios.',
    permissions: ['dashboard:view', 'indicators:view', 'actions:view', 'deviations:view', 'projects:view', 'strategy:view', 'okrs:view', 'org:view'],
  },
] as const;
