export const PERMISSION_CATALOG = [
  ['dashboard:view', 'Visualizar dashboards', 'Dashboard', 'view'],
  ['dashboard:export', 'Exportar dashboards', 'Dashboard', 'export'],
  ['launches:view', 'Visualizar lancamentos', 'Lancamentos', 'view'],
  ['results:launch', 'Lancar resultados', 'Lancamentos', 'create'],
  ['results:approve', 'Aprovar resultados', 'Lancamentos', 'approve'],
  ['indicators:view', 'Visualizar indicadores', 'Indicadores', 'view'],
  ['indicators:create', 'Criar indicadores', 'Indicadores', 'create'],
  ['indicators:update', 'Editar indicadores', 'Indicadores', 'update'],
  ['indicators:delete', 'Excluir indicadores', 'Indicadores', 'delete'],
  ['actions:view', 'Visualizar planos de acao', 'Planos de acao', 'view'],
  ['actions:manage', 'Gerenciar planos de acao', 'Planos de acao', 'manage'],
  ['actions:approve', 'Aprovar planos de acao', 'Planos de acao', 'approve'],
  ['deviations:view', 'Visualizar desvios e analises', 'Desvios', 'view'],
  ['deviations:manage', 'Gerenciar desvios e analises', 'Desvios', 'manage'],
  ['projects:view', 'Visualizar projetos', 'Projetos', 'view'],
  ['projects:manage', 'Gerenciar projetos', 'Projetos', 'manage'],
  ['meetings:view', 'Visualizar reunioes', 'Reunioes', 'view'],
  ['meetings:manage', 'Gerenciar reunioes', 'Reunioes', 'manage'],
  ['strategy:view', 'Visualizar mapa estrategico', 'Estrategia', 'view'],
  ['strategy:manage', 'Gerenciar mapa estrategico', 'Estrategia', 'manage'],
  ['strategy:maps:create', 'Criar mapas estrategicos', 'Estrategia', 'create'],
  ['strategy:maps:update', 'Editar mapas estrategicos', 'Estrategia', 'update'],
  ['strategy:maps:delete', 'Inativar mapas estrategicos', 'Estrategia', 'delete'],
  ['strategy:perspectives:create', 'Criar perspectivas estrategicas', 'Estrategia', 'create'],
  ['strategy:perspectives:update', 'Editar e reordenar perspectivas', 'Estrategia', 'update'],
  ['strategy:perspectives:delete', 'Inativar perspectivas estrategicas', 'Estrategia', 'delete'],
  ['strategy:objectives:create', 'Criar objetivos estrategicos', 'Estrategia', 'create'],
  ['strategy:objectives:update', 'Editar, mover e reordenar objetivos estrategicos', 'Estrategia', 'update'],
  ['strategy:objectives:delete', 'Inativar objetivos estrategicos', 'Estrategia', 'delete'],
  ['strategy:indicators:link', 'Vincular indicadores a objetivos estrategicos', 'Estrategia', 'link'],
  ['strategy:links:manage', 'Gerenciar ligacoes entre objetivos estrategicos', 'Estrategia', 'manage'],
  ['strategy:publish', 'Publicar versoes do mapa estrategico', 'Estrategia', 'publish'],
  ['strategy:history:view', 'Visualizar historico do mapa estrategico', 'Estrategia', 'view'],
  ['okrs:view', 'Visualizar OKRs', 'OKRs', 'view'],
  ['okrs:manage', 'Gerenciar OKRs', 'OKRs', 'manage'],
  ['org:view', 'Visualizar estrutura organizacional', 'Estrutura', 'view'],
  ['org:manage', 'Gerenciar estrutura organizacional', 'Estrutura', 'manage'],
  ['reports:export', 'Exportar relatorios', 'Relatorios', 'export'],
  ['settings:view', 'Visualizar configuracoes', 'Configuracoes', 'view'],
  ['settings:manage', 'Gerenciar parametros do sistema', 'Configuracoes', 'manage'],
  ['users:manage', 'Gerenciar usuarios e permissoes', 'Usuarios', 'manage'],
  ['audit:view', 'Visualizar auditoria', 'Auditoria', 'view'],
  ['audit:export', 'Exportar auditoria', 'Auditoria', 'export'],
] as const;

export const DEFAULT_PROFILES = [
  {
    code: 'SUPER_ADMIN',
    name: 'Super Admin',
    role: 'SUPER_ADMIN',
    description: 'Acesso total ao sistema, seguranca, auditoria e parametros.',
    permissions: PERMISSION_CATALOG.map(([key]) => key),
  },
  {
    code: 'ADMIN',
    name: 'Admin',
    role: 'COMPANY_ADMIN',
    description: 'Administracao da empresa com acesso a usuarios, estrutura e parametrizacao.',
    permissions: PERMISSION_CATALOG.map(([key]) => key).filter((key) => key !== 'audit:export'),
  },
  {
    code: 'GESTOR',
    name: 'Gestor',
    role: 'MANAGER',
    description: 'Gestao de indicadores, planos de acao e acompanhamentos do setor.',
    permissions: [
      'dashboard:view',
      'launches:view',
      'results:launch',
      'indicators:view',
      'indicators:create',
      'indicators:update',
      'actions:view',
      'actions:manage',
      'deviations:view',
      'deviations:manage',
      'meetings:view',
      'meetings:manage',
      'strategy:view',
      'reports:export',
      'org:view',
    ],
  },
  {
    code: 'USUARIO',
    name: 'Usuario',
    role: 'COLLABORATOR',
    description: 'Acesso operacional para lancamentos e execucao de atividades.',
    permissions: ['dashboard:view', 'launches:view', 'results:launch', 'indicators:view', 'actions:view', 'actions:manage', 'meetings:view'],
  },
  {
    code: 'VISUALIZADOR',
    name: 'Visualizador',
    role: 'VIEWER',
    description: 'Acesso somente leitura aos principais paineis e relatorios.',
    permissions: ['dashboard:view', 'indicators:view', 'actions:view', 'deviations:view', 'projects:view', 'strategy:view', 'okrs:view', 'org:view'],
  },
] as const;
