import { CATALOG_MODULES } from '../portal-admin/portal-catalog';
import { expandPlanModules } from '../portal-admin/business-modules';

export const PLATFORM_PERMISSIONS = [
  ['platform.*', 'Acesso total ao Portal Admin Global', 'Sistema', 'manage'],
  ['platform.dashboard.view', 'Visualizar dashboard global', 'Visao Geral', 'view'],
  ['platform.companies.view', 'Visualizar empresas', 'Empresas', 'view'],
  ['platform.companies.create', 'Cadastrar empresas', 'Empresas', 'create'],
  ['platform.companies.edit', 'Editar empresas', 'Empresas', 'edit'],
  ['platform.companies.suspend', 'Suspender ou reativar empresas', 'Empresas', 'suspend'],
  ['platform.modules.view', 'Visualizar catalogo e matriz de modulos', 'Modulos', 'view'],
  ['platform.modules.manage', 'Liberar, bloquear e configurar modulos', 'Modulos', 'manage'],
  ['platform.plans.view', 'Visualizar planos e contratos', 'Planos', 'view'],
  ['platform.plans.manage', 'Gerenciar planos, limites e contratos', 'Planos', 'manage'],
  ['platform.users.view', 'Visualizar usuarios globais', 'Usuarios', 'view'],
  ['platform.users.manage', 'Bloquear usuarios, revogar sessoes e convites', 'Usuarios', 'manage'],
  ['platform.access_logs.view', 'Visualizar sessoes e logs de acesso', 'Seguranca', 'view'],
  ['platform.audit_logs.view', 'Visualizar trilha de auditoria', 'Auditoria', 'view'],
  ['platform.database.read', 'Consultar explorador seguro do banco', 'Banco de Dados', 'read'],
  ['platform.database.health', 'Visualizar saude e integridade do banco', 'Banco de Dados', 'health'],
  ['platform.database.backup', 'Registrar e consultar backups', 'Banco de Dados', 'backup'],
  ['platform.database.restore_request', 'Solicitar restauracao controlada', 'Banco de Dados', 'restore_request'],
  ['platform.feature_flags.manage', 'Gerenciar feature flags e experimentos', 'Funcionalidades', 'manage'],
  ['platform.environments.manage', 'Gerenciar ambientes, versoes e releases', 'Ambientes', 'manage'],
  ['platform.support_mode.start', 'Iniciar modo seguro de suporte', 'Suporte', 'start'],
  ['platform.maintenance.manage', 'Gerenciar manutencoes da plataforma', 'Manutencao', 'manage'],
  ['platform.integrations.manage', 'Gerenciar integracoes globais', 'Integracoes', 'manage'],
  ['platform.jobs.manage', 'Visualizar e reprocessar jobs', 'Jobs', 'manage'],
  ['platform.internal_users.manage', 'Gerenciar usuarios internos da plataforma', 'Usuarios Internos', 'manage'],
] as const;

const ALL = PLATFORM_PERMISSIONS.map(([key]) => key);
const VIEW_ONLY = ALL.filter((key) => key.endsWith('.view') || key.endsWith('.health') || key.endsWith('.read'));

export const PLATFORM_ROLES = [
  {
    code: 'PLATFORM_OWNER',
    name: 'Platform Owner',
    description: 'Acesso maximo ao Portal Admin Global.',
    permissions: ['platform.*'],
  },
  {
    code: 'SUPER_ADMIN',
    name: 'Super Admin',
    description: 'Administra empresas, modulos, usuarios internos e operacao geral.',
    permissions: ALL.filter((key) => key !== 'platform.*'),
  },
  {
    code: 'IMPLEMENTATION_MANAGER',
    name: 'Gestor de Implantacao',
    description: 'Configura empresas, planos iniciais e modulos autorizados.',
    permissions: [
      'platform.dashboard.view',
      'platform.companies.view',
      'platform.companies.create',
      'platform.companies.edit',
      'platform.modules.view',
      'platform.modules.manage',
      'platform.plans.view',
      'platform.audit_logs.view',
    ],
  },
  {
    code: 'TECHNICAL_SUPPORT',
    name: 'Suporte Tecnico',
    description: 'Consulta configuracoes, logs e inicia suporte somente leitura.',
    permissions: [
      'platform.dashboard.view',
      'platform.companies.view',
      'platform.modules.view',
      'platform.users.view',
      'platform.access_logs.view',
      'platform.audit_logs.view',
      'platform.support_mode.start',
      'platform.integrations.manage',
    ],
  },
  {
    code: 'DATABASE_ADMIN',
    name: 'Administrador de Banco de Dados',
    description: 'Acompanha integridade, backups, migracoes e consultas controladas.',
    permissions: [
      'platform.dashboard.view',
      'platform.database.read',
      'platform.database.health',
      'platform.database.backup',
      'platform.database.restore_request',
      'platform.audit_logs.view',
    ],
  },
  {
    code: 'DEVELOPER',
    name: 'Desenvolvedor',
    description: 'Acessa logs tecnicos, ambientes, feature flags, jobs e diagnosticos.',
    permissions: [
      'platform.dashboard.view',
      'platform.modules.view',
      'platform.audit_logs.view',
      'platform.feature_flags.manage',
      'platform.environments.manage',
      'platform.integrations.manage',
      'platform.jobs.manage',
      'platform.database.health',
    ],
  },
  {
    code: 'COMMERCIAL_FINANCE',
    name: 'Comercial ou Financeiro',
    description: 'Administra planos, contratos, limites e modulos contratados.',
    permissions: [
      'platform.dashboard.view',
      'platform.companies.view',
      'platform.companies.edit',
      'platform.modules.view',
      'platform.plans.view',
      'platform.plans.manage',
      'platform.audit_logs.view',
    ],
  },
  {
    code: 'PLATFORM_AUDITOR',
    name: 'Auditor Interno da Plataforma',
    description: 'Consulta trilhas de auditoria e historicos sem alterar dados.',
    permissions: VIEW_ONLY,
  },
] as const;

export const PLATFORM_MODULE_STATUSES = [
  'ATIVO',
  'BLOQUEADO',
  'SUSPENSO',
  'SOMENTE_LEITURA',
  'EM_IMPLANTACAO',
  'EM_TESTE',
  'ATIVACAO_PROGRAMADA',
  'EXPIRACAO_PROGRAMADA',
  'EXPERIMENTAL',
  'HERDADO_DO_PLANO',
  'SOBRESCRITO_MANUALMENTE',
] as const;

export const PLATFORM_MODULES = CATALOG_MODULES.map((module) => ({
  code: module.code,
  name: module.name,
  description: module.description ?? null,
  category: module.category,
  icon: module.icon ?? null,
  route: module.route ?? null,
  version: '1.0.0',
  dependencies: module.dependencies ?? [],
  technicalOwner: module.systemRequired ? 'Core Platform' : 'Product Engineering',
  experimental: module.criticality === 'low' && ['insights', 'ai'].includes(module.code),
}));

export const PLATFORM_PLANS = [
  {
    code: 'ESSENCIAL',
    name: 'Essencial',
    setupPriceCents: 0,
    monthlyPriceCents: 99000,
    defaultUsers: 25,
    defaultBranches: 1,
    storageLimitMb: 10240,
    supportLevel: 'Padrao',
    sla: 'Proximo dia util',
    trialDays: 14,
    // Padrão (Meu Dia, Tarefas, Administração) + Gestão à Vista.
    modules: expandPlanModules('ESSENCIAL'),
  },
  {
    code: 'PROFISSIONAL',
    name: 'Profissional',
    setupPriceCents: 250000,
    monthlyPriceCents: 249000,
    defaultUsers: 80,
    defaultBranches: 5,
    storageLimitMb: 51200,
    supportLevel: 'Prioritario',
    sla: '8 horas uteis',
    trialDays: 21,
    // Padrão + Gestão à Vista + Qualidade e Compliance + Comunicação.
    modules: expandPlanModules('PROFISSIONAL'),
  },
  {
    code: 'CORPORATIVO',
    name: 'Corporativo',
    setupPriceCents: 500000,
    monthlyPriceCents: 599000,
    defaultUsers: 250,
    defaultBranches: 20,
    storageLimitMb: 204800,
    supportLevel: 'Dedicado',
    sla: '4 horas uteis',
    trialDays: 30,
    // Padrão + Gestão à Vista + Qualidade e Compliance + Comunicação + Cargos e Salários + Segurança (Alimentos e Patrimonial).
    modules: expandPlanModules('CORPORATIVO'),
  },
  {
    code: 'ENTERPRISE',
    name: 'Enterprise',
    setupPriceCents: 1000000,
    monthlyPriceCents: 1299000,
    defaultUsers: null,
    defaultBranches: null,
    storageLimitMb: null,
    supportLevel: 'SLA customizado',
    sla: 'Contrato especifico',
    trialDays: 30,
    // Tudo: Padrão + todas as abas de negócio (inclui Gestão de Prêmio).
    modules: expandPlanModules('ENTERPRISE'),
  },
  {
    code: 'PERSONALIZADO',
    name: 'Personalizado',
    setupPriceCents: 0,
    monthlyPriceCents: 0,
    defaultUsers: null,
    defaultBranches: null,
    storageLimitMb: null,
    supportLevel: 'Sob contrato',
    sla: 'Sob contrato',
    trialDays: null,
    modules: [],
  },
] as const;
