import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { AuditWriterService } from '../../common/audit/audit-writer.service';
import { PrismaService } from '../../prisma/prisma.service';
import { AuthPayload } from '../auth/auth.types';
import { InventoryService } from './inventory.service';
import { businessNumber } from './supplies.logic';

@Injectable()
export class AdvancedSuppliesService {
  constructor(private readonly prisma: PrismaService, private readonly inventory: InventoryService, private readonly audit: AuditWriterService) {}

  listMeasurements(me: AuthPayload, status?: string) { return this.prisma.serviceMeasurement.findMany({ where: { companyId: me.companyId, ...(status ? { status } : {}) }, include: { items: true }, orderBy: { createdAt: 'desc' }, take: 1000 }); }
  async createMeasurement(me: AuthPayload, body: any) {
    const order = await this.prisma.purchaseOrder.findFirst({ where: { id: body.purchaseOrderId, companyId: me.companyId, status: { in: ['APPROVED', 'SENT', 'PARTIALLY_DELIVERED', 'DELIVERED'] } }, include: { items: true } });
    if (!order) throw new NotFoundException('Pedido elegível não encontrado.');
    if (!(await this.prisma.user.findFirst({ where: { id: body.fiscalUserId, companyId: me.companyId, active: true, deletedAt: null } }))) throw new NotFoundException('Fiscal não encontrado.');
    const lines = body.items.map((input: any) => { const line = order.items.find((x) => x.id === input.purchaseOrderItemId && x.kindSnapshot === 'SERVICE'); if (!line) throw new NotFoundException('Item de serviço não encontrado.'); if (dec(input.quantity).gt(line.orderedQuantity)) throw new ConflictException('Quantidade medida supera a contratada.'); return { line, input }; });
    const row = await this.prisma.serviceMeasurement.create({ data: { companyId: me.companyId, number: businessNumber('BM'), purchaseOrderId: order.id, fiscalUserId: body.fiscalUserId, periodStart: new Date(body.periodStart), periodEnd: new Date(body.periodEnd), notes: clean(body.notes), createdById: me.sub, items: { create: lines.map(({ line, input }: any) => ({ companyId: me.companyId, purchaseOrderItemId: line.id, description: line.description, quantity: dec(input.quantity), unitPrice: line.unitPrice, totalPrice: dec(input.quantity).mul(line.unitPrice), note: clean(input.note) })) } }, include: { items: true } });
    await this.write(me, 'ServiceMeasurement', row.id, 'CREATE', `Medição ${row.number} criada`, row); return row;
  }
  async submitMeasurement(me: AuthPayload, id: string) { const row = await this.measurement(me, id); if (!['DRAFT', 'CONTESTED'].includes(row.status)) throw new ConflictException('Medição não pode ser enviada.'); return this.prisma.serviceMeasurement.update({ where: { id }, data: { status: 'SUBMITTED', submittedAt: new Date(), contestReason: null } }); }
  async approveMeasurement(me: AuthPayload, id: string, _body: any) { const row = await this.measurement(me, id); if (row.status !== 'SUBMITTED') throw new ConflictException('Medição precisa estar enviada.'); if (row.fiscalUserId !== me.sub && !admin(me)) throw new ForbiddenException('Somente o fiscal responsável pode aprovar.'); const result = await this.prisma.serviceMeasurement.update({ where: { id }, data: { status: 'APPROVED', approvedAt: new Date(), approvedById: me.sub } }); await this.write(me, 'ServiceMeasurement', id, 'APPROVE', `Medição ${row.number} aprovada`, result); return result; }
  async contestMeasurement(me: AuthPayload, id: string, body: any) { const row = await this.measurement(me, id); if (row.status !== 'SUBMITTED') throw new ConflictException('Medição precisa estar enviada.'); if (row.fiscalUserId !== me.sub && !admin(me)) throw new ForbiddenException('Somente o fiscal responsável pode contestar.'); return this.prisma.serviceMeasurement.update({ where: { id }, data: { status: 'CONTESTED', contestedAt: new Date(), contestedById: me.sub, contestReason: body.reason } }); }
  async createServiceInvoice(me: AuthPayload, body: any) {
    const measurement = await this.prisma.serviceMeasurement.findFirst({ where: { id: body.serviceMeasurementId, companyId: me.companyId }, include: { items: true } }); if (!measurement) throw new NotFoundException('Medição não encontrada.'); if (measurement.status !== 'APPROVED') throw new ConflictException('NF de serviço exige medição aprovada.');
    const order = await this.prisma.purchaseOrder.findFirst({ where: { id: measurement.purchaseOrderId, companyId: me.companyId }, include: { items: true } }); if (!order) throw new NotFoundException('Pedido não encontrado.');
    const total = measurement.items.reduce((sum, x) => sum.plus(x.totalPrice), dec(0));
    const invoice = await this.prisma.$transaction(async (tx) => { const created = await tx.supplierInvoice.create({ data: { companyId: me.companyId, kind: 'SERVICE', invoiceNumber: body.invoiceNumber, series: clean(body.series), accessKey: clean(body.accessKey), supplierId: order.supplierId, purchaseOrderId: order.id, serviceMeasurementId: measurement.id, issuedAt: new Date(body.issuedAt), totalAmount: total, attachmentDocumentId: body.attachmentDocumentId ?? null, notes: clean(body.notes), postedById: me.sub, items: { create: measurement.items.map((x) => { const po = order.items.find((i) => i.id === x.purchaseOrderItemId)!; return { companyId: me.companyId, purchaseOrderItemId: po.id, itemId: po.itemId, description: x.description, quantity: x.quantity, unitPrice: x.unitPrice, totalPrice: x.totalPrice }; }) } } }); await tx.serviceMeasurement.update({ where: { id: measurement.id }, data: { status: 'INVOICED', invoicedAt: new Date() } }); return created; }).catch(duplicate('Medição ou NF já faturada.'));
    await this.write(me, 'SupplierInvoice', invoice.id, 'POST_SERVICE', `NF ${invoice.invoiceNumber} vinculada à medição`, invoice); return invoice;
  }

  listCounts(me: AuthPayload) { return this.prisma.inventoryCount.findMany({ where: { companyId: me.companyId }, include: { items: true }, orderBy: { createdAt: 'desc' }, take: 500 }); }
  async createCount(me: AuthPayload, body: any) { const warehouse = await this.prisma.warehouse.findFirst({ where: { id: body.warehouseId, companyId: me.companyId, active: true, deletedAt: null } }); if (!warehouse) throw new NotFoundException('Almoxarifado não encontrado.'); const balances = await this.prisma.stockBalance.findMany({ where: { companyId: me.companyId, warehouseId: warehouse.id, ...(body.itemIds?.length ? { itemId: { in: body.itemIds } } : {}) } }); const row = await this.prisma.inventoryCount.create({ data: { companyId: me.companyId, number: businessNumber('INV'), warehouseId: warehouse.id, scheduledAt: body.scheduledAt ? new Date(body.scheduledAt) : null, reason: clean(body.reason), createdById: me.sub, items: { create: balances.map((x) => ({ companyId: me.companyId, itemId: x.itemId, expectedQuantity: x.quantity })) } }, include: { items: true } }); await this.write(me, 'InventoryCount', row.id, 'CREATE', `Inventário ${row.number} criado`, row); return row; }
  async startCount(me: AuthPayload, id: string) { const row = await this.count(me, id); if (row.status !== 'DRAFT') throw new ConflictException('Inventário não está em rascunho.'); return this.prisma.inventoryCount.update({ where: { id }, data: { status: 'COUNTING', startedAt: new Date() }, include: { items: true } }); }
  async recordCount(me: AuthPayload, id: string, body: any) { const row = await this.count(me, id); if (row.status !== 'COUNTING') throw new ConflictException('Inventário não está em contagem.'); for (const input of body.items) { const line = row.items.find((x) => x.id === input.inventoryCountItemId); if (!line) throw new NotFoundException('Linha não encontrada.'); await this.prisma.inventoryCountItem.update({ where: { id: line.id }, data: { countedQuantity: dec(input.countedQuantity), differenceQuantity: dec(input.countedQuantity).minus(line.expectedQuantity), countedById: me.sub, countedAt: new Date(), note: clean(input.note) } }); } return this.count(me, id); }
  async completeCount(me: AuthPayload, id: string, body: any) { const row = await this.count(me, id); if (row.status !== 'COUNTING') throw new ConflictException('Inventário não está em contagem.'); if (row.items.some((x) => x.countedQuantity == null)) throw new ConflictException('Todos os itens precisam ser contados.'); for (const line of row.items) if (line.differenceQuantity && !line.differenceQuantity.isZero()) await this.inventory.adjustStock(me, { warehouseId: row.warehouseId, itemId: line.itemId, quantityDelta: line.differenceQuantity, reason: `Inventário ${row.number}`, reference: row.number, idempotencyKey: `${body.idempotencyKey}:${line.id}` }); const result = await this.prisma.inventoryCount.update({ where: { id }, data: { status: 'COMPLETED', completedAt: new Date(), completedById: me.sub } }); await this.write(me, 'InventoryCount', id, 'COMPLETE', `Inventário ${row.number} concluído`, result); return result; }
  async abcCurve(me: AuthPayload, warehouseId?: string) { const rows = (await this.prisma.stockBalance.findMany({ where: { companyId: me.companyId, ...(warehouseId ? { warehouseId } : {}) }, include: { item: true, warehouse: true } })).map((x) => ({ ...x, stockValue: Number(x.quantity) * Number(x.averageCost) })).sort((a, b) => b.stockValue - a.stockValue); const total = rows.reduce((s, x) => s + x.stockValue, 0); let running = 0; return rows.map((x) => { running += x.stockValue; const p = total ? running / total : 0; return { ...x, cumulativePercentage: p * 100, abcClass: p <= .8 ? 'A' : p <= .95 ? 'B' : 'C' }; }); }
  async lookupQr(me: AuthPayload, token: string) { const item = await this.prisma.stockItem.findFirst({ where: { companyId: me.companyId, qrCodeToken: token, active: true, deletedAt: null } }); if (!item) throw new NotFoundException('QR não encontrado.'); return { item, balances: await this.prisma.stockBalance.findMany({ where: { companyId: me.companyId, itemId: item.id }, include: { warehouse: true } }) }; }
  listPolicies(me: AuthPayload) { return this.prisma.withdrawalApprovalPolicy.findMany({ where: { companyId: me.companyId, deletedAt: null }, orderBy: { createdAt: 'desc' } }); }
  async createPolicy(me: AuthPayload, body: any) { if (body.orgNodeId && !(await this.prisma.orgNode.findFirst({ where: { id: body.orgNodeId, companyId: me.companyId, deletedAt: null } }))) throw new NotFoundException('Área não encontrada.'); if (body.approverUserId && !(await this.prisma.user.findFirst({ where: { id: body.approverUserId, companyId: me.companyId, active: true, deletedAt: null } }))) throw new NotFoundException('Aprovador não encontrado.'); return this.prisma.withdrawalApprovalPolicy.create({ data: { companyId: me.companyId, name: body.name, orgNodeId: body.orgNodeId ?? null, minimumAmount: dec(body.minimumAmount), approverUserId: body.approverUserId ?? null, approverRole: body.approverRole ?? null, active: body.active ?? true, createdById: me.sub } }); }

  private measurement(me: AuthPayload, id: string) { return this.prisma.serviceMeasurement.findFirst({ where: { id, companyId: me.companyId }, include: { items: true } }).then((x) => { if (!x) throw new NotFoundException('Medição não encontrada.'); return x; }); }
  private count(me: AuthPayload, id: string) { return this.prisma.inventoryCount.findFirst({ where: { id, companyId: me.companyId }, include: { items: true } }).then((x) => { if (!x) throw new NotFoundException('Inventário não encontrado.'); return x; }); }
  private write(me: AuthPayload, entity: string, entityId: string, action: string, message: string, after: unknown) { return this.audit.record(me, { module: 'Suprimentos', entity, entityId, action, message, after }); }
}

function dec(v: unknown) { return new Prisma.Decimal(String(v ?? 0)); }
function clean(v: unknown): string | null { const s = String(v ?? '').trim(); return s || null; }
function admin(me: AuthPayload) { return ['SUPER_ADMIN', 'COMPANY_ADMIN'].includes(String(me.role)); }
function duplicate(message: string) { return (e: unknown) => { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new ConflictException(message); throw e; }; }
