/**
 * Catalogo-semente do registro do portal. Fonte para popular Portal{Module,Page,Feature}.
 * O sync e aditivo por code e atualiza apenas metadados controlados pelo produto.
 */

export interface CatalogModule {
  code: string;
  name: string;
  description?: string;
  category: string;
  icon?: string;
  route?: string;
  menuOrder: number;
  criticality: 'low' | 'medium' | 'high' | 'critical';
  systemRequired?: boolean;
  nonBlockable?: boolean;
  dependencies?: string[];
}

export interface CatalogPage {
  code: string;
  moduleCode: string;
  name: string;
  title: string;
  route: string;
  menuOrder?: number;
}

export interface CatalogFeature {
  code: string;
  moduleCode: string;
  name: string;
  criticality?: 'low' | 'medium' | 'high' | 'critical';
}

export const CATALOG_MODULES: CatalogModule[] = [
  { code: 'my-day', name: 'Meu Dia', category: 'Meu Dia', route: '/meu-dia', menuOrder: 10, criticality: 'medium' },
  { code: 'tasks', name: 'Tarefas', category: 'Tarefas', route: '/tarefas', menuOrder: 20, criticality: 'medium' },

  { code: 'visualization', name: 'Painel Executivo', category: 'Estrategia', route: '/visualization', menuOrder: 30, criticality: 'low' },
  { code: 'org', name: 'Arvore Organizacional', category: 'Estrategia', route: '/org', menuOrder: 31, criticality: 'medium' },
  { code: 'strategy', name: 'Mapa Estrategico', category: 'Estrategia', route: '/strategy', menuOrder: 32, criticality: 'medium' },
  { code: 'indicators', name: 'Indicadores', category: 'Estrategia', route: '/indicators', menuOrder: 33, criticality: 'high' },
  { code: 'deviations', name: 'Desvios', category: 'Estrategia', route: '/deviations', menuOrder: 34, criticality: 'medium' },
  { code: 'actions', name: 'Plano de Acao', category: 'Estrategia', route: '/actions', menuOrder: 35, criticality: 'high' },
  { code: 'meetings', name: 'Reunioes', category: 'Estrategia', route: '/meetings', menuOrder: 36, criticality: 'low' },
  { code: 'monthly-results', name: 'Reuniao Mensal', category: 'Estrategia', route: '/monthly-results', menuOrder: 37, criticality: 'medium' },
  { code: 'okrs', name: 'OKRs', category: 'Estrategia', route: '/okrs', menuOrder: 38, criticality: 'low' },

  { code: 'aprovacoes-cargo', name: 'Aprovacoes', category: 'Administracao', route: '/aprovacoes-cargo', menuOrder: 40, criticality: 'medium' },
  { code: 'periods', name: 'Periodos', category: 'Administracao', route: '/periods', menuOrder: 41, criticality: 'high' },
  { code: 'automations', name: 'Central de Automacoes', category: 'Administracao', route: '/central-automacoes', menuOrder: 42, criticality: 'medium' },
  { code: 'users', name: 'Usuarios', category: 'Administracao', route: '/users', menuOrder: 43, criticality: 'critical', systemRequired: true, nonBlockable: true },
  { code: 'reports', name: 'Relatorios e Exportacoes', category: 'Administracao', route: '/reports', menuOrder: 44, criticality: 'medium' },

  { code: 'risks', name: 'Riscos', category: 'Qualidade e Compliance', route: '/risks', menuOrder: 50, criticality: 'high' },
  { code: 'nonconformities', name: 'Nao Conformidades', category: 'Qualidade e Compliance', route: '/nonconformities', menuOrder: 51, criticality: 'high' },
  { code: 'audits', name: 'Auditorias', category: 'Qualidade e Compliance', route: '/audits', menuOrder: 52, criticality: 'high' },
  { code: 'documents', name: 'Documentos', category: 'Qualidade e Compliance', route: '/documents', menuOrder: 53, criticality: 'medium' },
  { code: 'processes', name: 'Processos', category: 'Qualidade e Compliance', route: '/processes', menuOrder: 54, criticality: 'medium' },
  { code: 'forms', name: 'Formularios', category: 'Qualidade e Compliance', route: '/forms', menuOrder: 55, criticality: 'medium' },
  { code: 'projects', name: 'Cronogramas', category: 'Qualidade e Compliance', route: '/projects', menuOrder: 56, criticality: 'low' },
  { code: 'vision360', name: 'Impactos', category: 'Qualidade e Compliance', route: '/central-impactos', menuOrder: 57, criticality: 'medium' },

  { code: 'food-safety', name: 'Seguranca dos Alimentos', description: 'FSMS, APPCC, processos, perigos, cadeia e inteligencia', category: 'Seguranca dos Alimentos', route: '/seguranca-alimentos', menuOrder: 60, criticality: 'medium' },
  { code: 'asset-security', name: 'Seguranca Patrimonial', category: 'Seguranca Patrimonial', route: '/seguranca-patrimonial', menuOrder: 70, criticality: 'high' },
  { code: 'compensation', name: 'Cargos e Salarios', description: 'Plano de cargos, quadro, tabelas salariais e movimentacoes', category: 'Cargos e Salarios', route: '/cargos-salarios', menuOrder: 80, criticality: 'high' },
  { code: 'recruitment', name: 'Recrutamento e Selecao', description: 'Requisicoes de vaga, divulgacao, candidatos, propostas, pre-admissao e admissao (inclui portal publico de carreiras)', category: 'Recrutamento e Selecao', route: '/recrutamento', menuOrder: 83, criticality: 'high' },
  { code: 'personnel', name: 'Servico Pessoal', description: 'Departamento pessoal: colaboradores, ponto (inclusive totem facial), ferias, admissoes e fechamento de competencia', category: 'Servico Pessoal', route: '/servico-pessoal/colaboradores', menuOrder: 85, criticality: 'high' },
  { code: 'payroll', name: 'Folha de Pagamento', description: 'Motor de calculo, beneficios, rescisoes, eSocial, CNAB, obrigacoes e holerites', category: 'Servico Pessoal', route: '/servico-pessoal/folha', menuOrder: 86, criticality: 'critical' },
  { code: 'procurement', name: 'Compras', description: 'Requisicoes, fila do comprador, pedidos, alcadas e recebimentos', category: 'Suprimentos', route: '/suprimentos?tab=requisitions', menuOrder: 87, criticality: 'high' },
  { code: 'inventory', name: 'Estoque e Almoxarifado', description: 'Saldos, kardex, retiradas, transferencias e alertas de reposicao', category: 'Suprimentos', route: '/suprimentos?tab=stock', menuOrder: 88, criticality: 'high' },
  { code: 'communication', name: 'Comunicacao', category: 'Comunicacao', route: '/comunicacao', menuOrder: 90, criticality: 'medium' },
  { code: 'prize', name: 'Gestao de Premio', description: 'Remuneracao variavel: anexos, competencias, apuracao, folha e espelho', category: 'Gestao de Premio', route: '/gestao-premio', menuOrder: 100, criticality: 'high' },
  { code: 'service-desk', name: 'Central de Atendimento', description: 'Chamados de suporte dos usuarios para a operacao do portal', category: 'Atendimento', route: '/central-atendimento', menuOrder: 105, criticality: 'medium' },

  { code: 'settings', name: 'Configuracoes', category: 'Portal Global', route: '/settings', menuOrder: 200, criticality: 'critical', systemRequired: true, nonBlockable: true },
  { code: 'database-admin', name: 'Administracao do Banco', category: 'Portal Global', route: '/settings/database', menuOrder: 201, criticality: 'critical', systemRequired: true, nonBlockable: true },
  { code: 'portal-admin', name: 'Central de Administracao do Portal', category: 'Portal Global', route: '/settings/portal', menuOrder: 202, criticality: 'critical', systemRequired: true, nonBlockable: true },
  { code: 'integrations', name: 'Integracoes Globais', category: 'Portal Global', route: '/integracoes', menuOrder: 203, criticality: 'medium' },
  { code: 'audit', name: 'Auditoria', category: 'Portal Global', route: '/audit', menuOrder: 204, criticality: 'critical', systemRequired: true, nonBlockable: true },
  { code: 'auth', name: 'Autenticacao', category: 'Sistema', menuOrder: 300, criticality: 'critical', systemRequired: true, nonBlockable: true },
  { code: 'access-control', name: 'Controle de Acesso', category: 'Sistema', menuOrder: 301, criticality: 'critical', systemRequired: true, nonBlockable: true },

  { code: 'dashboard', name: 'Dashboard legado', category: 'Legado', route: '/dashboard', menuOrder: 900, criticality: 'low' },
  { code: 'imports', name: 'Importacoes', category: 'Legado', route: '/imports', menuOrder: 901, criticality: 'low' },
  { code: 'treatments', name: 'Tratativas', category: 'Legado', route: '/treatments', menuOrder: 902, criticality: 'medium' },
  { code: 'eficacia', name: 'Analise de Eficacia', category: 'Legado', route: '/eficacia', menuOrder: 903, criticality: 'medium' },
  { code: 'insights', name: 'Insights', category: 'Legado', route: '/insights', menuOrder: 904, criticality: 'low' },
  { code: 'directory', name: 'Pessoas', category: 'Legado', route: '/pessoas', menuOrder: 905, criticality: 'low' },
  { code: 'help-center', name: 'Central de Ajuda', category: 'Legado', route: '/ajuda', menuOrder: 906, criticality: 'low' },
];

export const CATALOG_PAGES: CatalogPage[] = [
  { code: 'my-day.main', moduleCode: 'my-day', name: 'Meu Dia', title: 'Meu Dia', route: '/meu-dia', menuOrder: 10 },
  { code: 'my-day.team', moduleCode: 'my-day', name: 'Meu Dia da Equipe', title: 'Meu Dia da Equipe', route: '/meu-dia/equipe', menuOrder: 11 },
  { code: 'tasks.main', moduleCode: 'tasks', name: 'Tarefas', title: 'Tarefas', route: '/tarefas', menuOrder: 20 },

  { code: 'visualization.main', moduleCode: 'visualization', name: 'Painel Executivo', title: 'Painel Executivo', route: '/visualization', menuOrder: 30 },
  { code: 'org.main', moduleCode: 'org', name: 'Arvore Organizacional', title: 'Arvore Organizacional', route: '/org', menuOrder: 31 },
  { code: 'strategy.main', moduleCode: 'strategy', name: 'Mapa Estrategico', title: 'Mapa Estrategico', route: '/strategy', menuOrder: 32 },
  { code: 'strategy.detail', moduleCode: 'strategy', name: 'Detalhe da Estrategia', title: 'Objetivo Estrategico', route: '/strategy/[id]', menuOrder: 32.1 },
  { code: 'indicators.list', moduleCode: 'indicators', name: 'Indicadores', title: 'Indicadores', route: '/indicators', menuOrder: 33 },
  { code: 'indicators.new', moduleCode: 'indicators', name: 'Novo Indicador', title: 'Novo Indicador', route: '/indicators/new', menuOrder: 33.01 },
  { code: 'indicators.detail', moduleCode: 'indicators', name: 'Detalhe do indicador', title: 'Indicador', route: '/indicators/[id]', menuOrder: 33 },
  { code: 'deviations.list', moduleCode: 'deviations', name: 'Desvios', title: 'Desvios', route: '/deviations', menuOrder: 34 },
  { code: 'deviations.detail', moduleCode: 'deviations', name: 'Detalhe do Desvio', title: 'Desvio', route: '/deviations/[id]', menuOrder: 34.1 },
  { code: 'actions.list', moduleCode: 'actions', name: 'Plano de Acao', title: 'Plano de Acao', route: '/actions', menuOrder: 35 },
  { code: 'actions.detail', moduleCode: 'actions', name: 'Detalhe da Acao', title: 'Acao', route: '/actions/[id]', menuOrder: 35.1 },
  { code: 'meetings.list', moduleCode: 'meetings', name: 'Reunioes', title: 'Reunioes', route: '/meetings', menuOrder: 36 },
  { code: 'meetings.detail', moduleCode: 'meetings', name: 'Detalhe da Reuniao', title: 'Reuniao', route: '/meetings/[id]', menuOrder: 36.1 },
  { code: 'monthly-results.main', moduleCode: 'monthly-results', name: 'Reuniao Mensal', title: 'Reuniao Mensal', route: '/monthly-results', menuOrder: 37 },
  { code: 'monthly-results.detail', moduleCode: 'monthly-results', name: 'Detalhe da Reuniao Mensal', title: 'Resultado Mensal', route: '/monthly-results/[id]', menuOrder: 37.1 },
  { code: 'okrs.main', moduleCode: 'okrs', name: 'OKRs', title: 'OKRs', route: '/okrs', menuOrder: 38 },

  { code: 'approvals.main', moduleCode: 'aprovacoes-cargo', name: 'Aprovacoes', title: 'Aprovacoes', route: '/aprovacoes-cargo', menuOrder: 40 },
  { code: 'periods.main', moduleCode: 'periods', name: 'Periodos', title: 'Periodos', route: '/periods', menuOrder: 41 },
  { code: 'automations.flows', moduleCode: 'automations', name: 'Central de Automacoes', title: 'Automacoes', route: '/central-automacoes', menuOrder: 42 },
  { code: 'automations.flow-list', moduleCode: 'automations', name: 'Fluxos', title: 'Fluxos de Automacao', route: '/central-automacoes/fluxos', menuOrder: 42.001 },
  { code: 'automations.library', moduleCode: 'automations', name: 'Biblioteca', title: 'Biblioteca de Automacoes', route: '/central-automacoes/biblioteca', menuOrder: 42.01 },
  { code: 'automations.models', moduleCode: 'automations', name: 'Modelos', title: 'Modelos de Automacao', route: '/central-automacoes/modelos', menuOrder: 42.02 },
  { code: 'automations.executions', moduleCode: 'automations', name: 'Execucoes', title: 'Execucoes de Automacao', route: '/central-automacoes/execucoes', menuOrder: 42.03 },
  { code: 'automations.approvals', moduleCode: 'automations', name: 'Aprovacoes', title: 'Aprovacoes de Automacao', route: '/central-automacoes/aprovacoes', menuOrder: 42.04 },
  { code: 'automations.tasks', moduleCode: 'automations', name: 'Tarefas', title: 'Tarefas de Automacao', route: '/central-automacoes/tarefas', menuOrder: 42.05 },
  { code: 'automations.failures', moduleCode: 'automations', name: 'Falhas', title: 'Falhas de Automacao', route: '/central-automacoes/falhas', menuOrder: 42.06 },
  { code: 'automations.escalations', moduleCode: 'automations', name: 'Escalonamentos', title: 'Escalonamentos', route: '/central-automacoes/escalonamentos', menuOrder: 42.07 },
  { code: 'automations.integrations', moduleCode: 'automations', name: 'Integracoes', title: 'Integracoes de Automacao', route: '/central-automacoes/integracoes', menuOrder: 42.08 },
  { code: 'automations.permissions', moduleCode: 'automations', name: 'Permissoes', title: 'Permissoes de Automacao', route: '/central-automacoes/permissoes', menuOrder: 42.09 },
  { code: 'automations.history', moduleCode: 'automations', name: 'Historico', title: 'Historico de Automacao', route: '/central-automacoes/historico', menuOrder: 42.1 },
  { code: 'automations.settings', moduleCode: 'automations', name: 'Configuracoes', title: 'Configuracoes de Automacao', route: '/central-automacoes/configuracoes', menuOrder: 42.11 },
  { code: 'automations.builder', moduleCode: 'automations', name: 'Construtor de Fluxo', title: 'Construtor de Fluxo', route: '/central-automacoes/fluxos/construtor', menuOrder: 42 },
  { code: 'users.main', moduleCode: 'users', name: 'Usuarios', title: 'Usuarios', route: '/users', menuOrder: 43 },
  { code: 'reports.list', moduleCode: 'reports', name: 'Relatorios e Exportacoes', title: 'Relatorios e Exportacoes', route: '/reports', menuOrder: 44 },

  { code: 'risks.list', moduleCode: 'risks', name: 'Riscos', title: 'Registro de Riscos', route: '/risks', menuOrder: 50 },
  { code: 'nonconformities.list', moduleCode: 'nonconformities', name: 'Nao Conformidades', title: 'Nao Conformidades', route: '/nonconformities', menuOrder: 51 },
  { code: 'audits.list', moduleCode: 'audits', name: 'Auditorias', title: 'Auditorias e Compliance', route: '/audits', menuOrder: 52 },
  { code: 'documents.list', moduleCode: 'documents', name: 'Documentos', title: 'Gestao Documental', route: '/documents', menuOrder: 53 },
  { code: 'processes.workflow', moduleCode: 'processes', name: 'Processos', title: 'Processos', route: '/processes', menuOrder: 54 },
  { code: 'forms.list', moduleCode: 'forms', name: 'Formularios', title: 'Formularios e Checklists', route: '/forms', menuOrder: 55 },
  { code: 'projects.list', moduleCode: 'projects', name: 'Cronogramas', title: 'Cronogramas', route: '/projects', menuOrder: 56 },
  { code: 'projects.detail', moduleCode: 'projects', name: 'Detalhe do Cronograma', title: 'Cronograma', route: '/projects/[id]', menuOrder: 56.1 },
  { code: 'vision360.impacts', moduleCode: 'vision360', name: 'Impactos', title: 'Central de Impactos', route: '/central-impactos', menuOrder: 57 },

  { code: 'food-safety.flow', moduleCode: 'food-safety', name: 'Fluxograma', title: 'Fluxograma', route: '/seguranca-alimentos?tab=flow', menuOrder: 60 },
  { code: 'food-safety.overview', moduleCode: 'food-safety', name: 'Visao Geral', title: 'Seguranca dos Alimentos', route: '/seguranca-alimentos?tab=overview', menuOrder: 61 },
  { code: 'food-safety.processes', moduleCode: 'food-safety', name: 'Processos', title: 'Processos', route: '/seguranca-alimentos?tab=processes', menuOrder: 62 },
  { code: 'food-safety.hazards', moduleCode: 'food-safety', name: 'Perigos / APPCC', title: 'Perigos / APPCC', route: '/seguranca-alimentos?tab=hazards', menuOrder: 63 },
  { code: 'food-safety.monitoring', moduleCode: 'food-safety', name: 'Monitoramento', title: 'Monitoramento', route: '/seguranca-alimentos?tab=monitoring', menuOrder: 64 },
  { code: 'food-safety.compliance', moduleCode: 'food-safety', name: 'Compliance', title: 'Compliance', route: '/seguranca-alimentos?tab=compliance', menuOrder: 65 },
  { code: 'food-safety.chain', moduleCode: 'food-safety', name: 'Cadeia e Recall', title: 'Cadeia e Recall', route: '/seguranca-alimentos?tab=chain', menuOrder: 66 },
  { code: 'food-safety.intelligence', moduleCode: 'food-safety', name: 'Inteligencia', title: 'Inteligencia', route: '/seguranca-alimentos?tab=intelligence', menuOrder: 67 },
  { code: 'food-safety.matrix', moduleCode: 'food-safety', name: 'Matriz Geral', title: 'Matriz Geral', route: '/seguranca-alimentos?tab=matrix', menuOrder: 68 },

  { code: 'asset-security.operation', moduleCode: 'asset-security', name: 'Operacao', title: 'Operacao', route: '/seguranca-patrimonial?tab=operation', menuOrder: 70 },
  { code: 'asset-security.people', moduleCode: 'asset-security', name: 'Pessoas e Veiculos', title: 'Pessoas e Veiculos', route: '/seguranca-patrimonial?tab=people', menuOrder: 71 },
  { code: 'asset-security.authorizations', moduleCode: 'asset-security', name: 'Autorizacoes', title: 'Autorizacoes', route: '/seguranca-patrimonial?tab=authorizations', menuOrder: 72 },
  { code: 'asset-security.rounds', moduleCode: 'asset-security', name: 'Rondas e Ocorrencias', title: 'Rondas e Ocorrencias', route: '/seguranca-patrimonial?tab=rounds', menuOrder: 73 },
  { code: 'asset-security.assets', moduleCode: 'asset-security', name: 'Materiais e Chaves', title: 'Materiais e Chaves', route: '/seguranca-patrimonial?tab=assets', menuOrder: 74 },
  { code: 'asset-security.settings', moduleCode: 'asset-security', name: 'Configuracoes', title: 'Configuracoes', route: '/seguranca-patrimonial?tab=settings', menuOrder: 75 },

  { code: 'compensation.overview', moduleCode: 'compensation', name: 'Visao Geral', title: 'Cargos e Salarios', route: '/cargos-salarios', menuOrder: 80 },
  { code: 'compensation.hierarchy', moduleCode: 'compensation', name: 'Hierarquia de Cargos', title: 'Hierarquia de Cargos', route: '/cargos-salarios/hierarquia', menuOrder: 80.5 },
  { code: 'compensation.org-chart', moduleCode: 'compensation', name: 'Organograma de Posicoes', title: 'Organograma', route: '/organograma', menuOrder: 80.6 },
  { code: 'compensation.structure', moduleCode: 'compensation', name: 'Estrutura e Quadro', title: 'Estrutura e Quadro', route: '/cargos-salarios/estrutura-quadro', menuOrder: 81 },
  { code: 'compensation.jobs', moduleCode: 'compensation', name: 'Catalogo de Cargos', title: 'Catalogo de Cargos', route: '/cargos-salarios/catalogo', menuOrder: 82 },
  { code: 'compensation.descriptions', moduleCode: 'compensation', name: 'Descricoes', title: 'Descricoes', route: '/cargos-salarios/descricoes', menuOrder: 83 },
  { code: 'compensation.salary-tables', moduleCode: 'compensation', name: 'Tabelas Salariais', title: 'Tabelas Salariais', route: '/cargos-salarios/tabelas-salariais', menuOrder: 84 },
  { code: 'compensation.salary-fit', moduleCode: 'compensation', name: 'Enquadramento', title: 'Enquadramento', route: '/cargos-salarios/enquadramento', menuOrder: 85 },
  { code: 'compensation.movements', moduleCode: 'compensation', name: 'Movimentacoes', title: 'Movimentacoes', route: '/cargos-salarios/movimentacoes', menuOrder: 86 },
  { code: 'compensation.cycles', moduleCode: 'compensation', name: 'Ciclos de Merito', title: 'Ciclos de Merito', route: '/cargos-salarios/ciclos', menuOrder: 87 },
  { code: 'compensation.budget', moduleCode: 'compensation', name: 'Orcamento de Pessoal', title: 'Orcamento de Pessoal', route: '/cargos-salarios/orcamento', menuOrder: 88 },
  { code: 'compensation.surveys', moduleCode: 'compensation', name: 'Pesquisas Salariais', title: 'Pesquisas Salariais', route: '/cargos-salarios/pesquisas', menuOrder: 89 },
  { code: 'compensation.simulations', moduleCode: 'compensation', name: 'Simulacoes', title: 'Simulacoes', route: '/cargos-salarios/simulacoes', menuOrder: 90 },
  { code: 'compensation.approvals', moduleCode: 'compensation', name: 'Aprovacoes', title: 'Aprovacoes', route: '/cargos-salarios/aprovacoes', menuOrder: 91 },
  { code: 'compensation.settings', moduleCode: 'compensation', name: 'Configuracoes', title: 'Configuracoes', route: '/cargos-salarios/configuracoes', menuOrder: 92 },
  { code: 'compensation.reports', moduleCode: 'compensation', name: 'Relatorios', title: 'Relatorios', route: '/cargos-salarios/relatorios', menuOrder: 93 },
  { code: 'compensation.equity', moduleCode: 'compensation', name: 'Equidade Salarial', title: 'Equidade Salarial (Lei 14.611)', route: '/cargos-salarios/equidade', menuOrder: 93.5 },

  { code: 'recruitment.requisitions', moduleCode: 'recruitment', name: 'Requisicoes e Aprovacoes', title: 'Requisicoes e Aprovacoes', route: '/recrutamento', menuOrder: 93.6 },
  { code: 'recruitment.jobs', moduleCode: 'recruitment', name: 'Vagas e Candidatos', title: 'Vagas e Candidatos', route: '/recrutamento/vagas', menuOrder: 93.7 },
  { code: 'recruitment.job-detail', moduleCode: 'recruitment', name: 'Detalhe da Vaga', title: 'Vaga e Pipeline', route: '/recrutamento/vagas/[id]', menuOrder: 93.71 },
  { code: 'recruitment.talent-pool', moduleCode: 'recruitment', name: 'Banco de Talentos', title: 'Banco de Talentos', route: '/recrutamento/talentos', menuOrder: 93.72 },
  { code: 'recruitment.analytics', moduleCode: 'recruitment', name: 'Analises de Recrutamento', title: 'Analises de Recrutamento', route: '/recrutamento/analises', menuOrder: 93.73 },
  { code: 'recruitment.communication', moduleCode: 'recruitment', name: 'Comunicacao com Candidatos', title: 'Comunicacao com Candidatos', route: '/recrutamento/comunicacao', menuOrder: 93.74 },
  { code: 'recruitment.internal-jobs', moduleCode: 'recruitment', name: 'Vagas Internas', title: 'Vagas Internas', route: '/vagas-internas', menuOrder: 93.75 },
  { code: 'recruitment.lgpd', moduleCode: 'recruitment', name: 'Privacidade e LGPD', title: 'Privacidade e LGPD', route: '/recrutamento/lgpd', menuOrder: 93.8 },
  { code: 'recruitment.careers', moduleCode: 'recruitment', name: 'Portal de Carreiras (publico)', title: 'Carreiras', route: '/carreiras', menuOrder: 93.9 },

  { code: 'personnel.overview', moduleCode: 'personnel', name: 'Visao Geral', title: 'Servico Pessoal', route: '/servico-pessoal', menuOrder: 93.99 },
  { code: 'personnel.employees', moduleCode: 'personnel', name: 'Colaboradores', title: 'Colaboradores', route: '/servico-pessoal/colaboradores', menuOrder: 94 },
  { code: 'personnel.time-clock', moduleCode: 'personnel', name: 'Controle de Ponto', title: 'Controle de Ponto', route: '/servico-pessoal/ponto', menuOrder: 95 },
  { code: 'personnel.facial', moduleCode: 'personnel', name: 'Ponto Facial (PWA)', title: 'Ponto Facial', route: '/servico-pessoal/ponto-facial', menuOrder: 95.1 },
  { code: 'personnel.kiosk', moduleCode: 'personnel', name: 'Totem de Reconhecimento Facial', title: 'Totem', route: '/totem', menuOrder: 95.2 },
  { code: 'personnel.vacations', moduleCode: 'personnel', name: 'Ferias e Afastamentos', title: 'Ferias e Afastamentos', route: '/servico-pessoal/ferias', menuOrder: 95.5 },
  { code: 'personnel.lifecycle', moduleCode: 'personnel', name: 'Admissao, Desligamento e ASO', title: 'Admissao, Desligamento e ASO', route: '/servico-pessoal/admissoes', menuOrder: 95.7 },
  { code: 'personnel.self-service', moduleCode: 'personnel', name: 'Minha Vida Funcional', title: 'Minha Vida Funcional', route: '/servico-pessoal/meu-holerite', menuOrder: 95.8 },
  { code: 'personnel.reports', moduleCode: 'personnel', name: 'Relatorios de DP', title: 'Relatorios de DP', route: '/servico-pessoal/relatorios', menuOrder: 95.85 },
  { code: 'personnel.settings', moduleCode: 'personnel', name: 'Configuracoes do DP', title: 'Configuracoes do Servico Pessoal', route: '/servico-pessoal/configuracoes', menuOrder: 95.9 },

  { code: 'payroll.overview', moduleCode: 'payroll', name: 'Folha de Pagamento', title: 'Folha de Pagamento', route: '/servico-pessoal/folha', menuOrder: 95.91 },
  { code: 'payroll.runs', moduleCode: 'payroll', name: 'Lotes de Calculo', title: 'Lote de Folha', route: '/servico-pessoal/folha/runs/[id]', menuOrder: 95.92 },
  { code: 'payroll.workers', moduleCode: 'payroll', name: 'Ficha Financeira do Colaborador', title: 'Colaborador na Folha', route: '/servico-pessoal/folha/workers/[id]', menuOrder: 95.925 },
  { code: 'payroll.benefits', moduleCode: 'payroll', name: 'Beneficios e Descontos', title: 'Beneficios e Descontos', route: '/servico-pessoal/folha/beneficios', menuOrder: 95.93 },
  { code: 'payroll.terminations', moduleCode: 'payroll', name: 'Rescisoes', title: 'Rescisoes e Desligamentos', route: '/servico-pessoal/folha/rescisao', menuOrder: 95.94 },
  { code: 'payroll.vacations', moduleCode: 'payroll', name: 'Ferias na Folha', title: 'Ferias na Folha', route: '/servico-pessoal/folha/ferias', menuOrder: 95.95 },
  { code: 'payroll.thirteenth', moduleCode: 'payroll', name: '13o Salario', title: '13o Salario', route: '/servico-pessoal/folha/decimo-terceiro', menuOrder: 95.96 },
  { code: 'payroll.params', moduleCode: 'payroll', name: 'Parametros de Folha', title: 'Parametros de Folha', route: '/servico-pessoal/folha/parametros', menuOrder: 95.97 },
  { code: 'payroll.esocial', moduleCode: 'payroll', name: 'eSocial', title: 'eSocial', route: '/servico-pessoal/folha/esocial', menuOrder: 95.98 },
  { code: 'payroll.bank', moduleCode: 'payroll', name: 'Remessa Bancaria (CNAB)', title: 'Remessa Bancaria', route: '/servico-pessoal/folha/banco', menuOrder: 95.985 },
  { code: 'payroll.obligations', moduleCode: 'payroll', name: 'Obrigacoes Trabalhistas', title: 'Obrigacoes Trabalhistas', route: '/servico-pessoal/folha/obrigacoes', menuOrder: 95.99 },
  { code: 'payroll.analytics', moduleCode: 'payroll', name: 'Gestao a Vista da Folha', title: 'Gestao a Vista da Folha', route: '/servico-pessoal/folha/gestao-a-vista', menuOrder: 95.995 },
  { code: 'procurement.dashboard', moduleCode: 'procurement', name: 'Painel de Suprimentos', title: 'Suprimentos', route: '/suprimentos?tab=dashboard', menuOrder: 96 },
  { code: 'procurement.requisitions', moduleCode: 'procurement', name: 'Requisicoes', title: 'Requisicoes de Compra', route: '/suprimentos?tab=requisitions', menuOrder: 97 },
  { code: 'procurement.orders', moduleCode: 'procurement', name: 'Pedidos', title: 'Pedidos de Compra', route: '/suprimentos?tab=orders', menuOrder: 98 },
  { code: 'inventory.stock', moduleCode: 'inventory', name: 'Estoque', title: 'Posicao e Kardex', route: '/suprimentos?tab=stock', menuOrder: 99 },
  { code: 'inventory.warehouse', moduleCode: 'inventory', name: 'Almoxarifado', title: 'Almoxarifado', route: '/suprimentos?tab=warehouse', menuOrder: 100 },
  { code: 'procurement.registrations', moduleCode: 'procurement', name: 'Cadastros', title: 'Cadastros de Suprimentos', route: '/suprimentos?tab=registrations', menuOrder: 101 },

  { code: 'communication.wall', moduleCode: 'communication', name: 'Meu Mural', title: 'Meu Mural', route: '/comunicacao?tab=mural', menuOrder: 100 },
  { code: 'communication.central', moduleCode: 'communication', name: 'Central', title: 'Central', route: '/comunicacao?tab=central', menuOrder: 101 },
  { code: 'communication.create', moduleCode: 'communication', name: 'Criar', title: 'Criar Comunicado', route: '/comunicacao?tab=criar', menuOrder: 102 },
  { code: 'communication.campaigns', moduleCode: 'communication', name: 'Campanhas', title: 'Campanhas', route: '/comunicacao?tab=campanhas', menuOrder: 103 },
  { code: 'communication.media', moduleCode: 'communication', name: 'Midias', title: 'Midias', route: '/comunicacao?tab=midias', menuOrder: 104 },
  { code: 'communication.metrics', moduleCode: 'communication', name: 'Metricas', title: 'Metricas', route: '/comunicacao?tab=metricas', menuOrder: 105 },
  { code: 'communication.chat', moduleCode: 'communication', name: 'Chat', title: 'Chat', route: '/comunicacao?tab=chat', menuOrder: 106 },

  { code: 'prize.overview', moduleCode: 'prize', name: 'Visao Geral do Premio', title: 'Gestao de Premio', route: '/gestao-premio', menuOrder: 110 },
  { code: 'prize.programs', moduleCode: 'prize', name: 'Programas de Premio', title: 'Programas de Premio', route: '/gestao-premio/programas', menuOrder: 111 },
  { code: 'prize.competences', moduleCode: 'prize', name: 'Competencias', title: 'Competencias', route: '/gestao-premio/competencias', menuOrder: 112 },
  { code: 'prize.annexes', moduleCode: 'prize', name: 'Anexos e Regras', title: 'Anexos e Regras', route: '/gestao-premio/anexos', menuOrder: 113 },
  { code: 'prize.indicators', moduleCode: 'prize', name: 'Indicadores do Premio', title: 'Indicadores do Premio', route: '/gestao-premio/indicadores', menuOrder: 113.1 },
  { code: 'prize.moderators', moduleCode: 'prize', name: 'Moderadores', title: 'Moderadores do Premio', route: '/gestao-premio/moderadores', menuOrder: 113.2 },
  { code: 'prize.actuals', moduleCode: 'prize', name: 'Realizado', title: 'Realizado', route: '/gestao-premio/realizado', menuOrder: 114 },
  { code: 'prize.forecast-vs-actual', moduleCode: 'prize', name: 'Previsto x Realizado', title: 'Previsto x Realizado', route: '/gestao-premio/previsto-realizado', menuOrder: 114.1 },
  { code: 'prize.eligible', moduleCode: 'prize', name: 'Colaboradores Elegiveis', title: 'Colaboradores Elegiveis', route: '/gestao-premio/colaboradores', menuOrder: 115 },
  { code: 'prize.calc', moduleCode: 'prize', name: 'Apuracao Mensal', title: 'Apuracao Mensal', route: '/gestao-premio/apuracao', menuOrder: 116 },
  { code: 'prize.adjustments', moduleCode: 'prize', name: 'Ajustes e Excecoes', title: 'Ajustes e Excecoes', route: '/gestao-premio/ajustes', menuOrder: 117 },
  { code: 'prize.payslips', moduleCode: 'prize', name: 'Espelhos do Premio', title: 'Espelhos do Premio', route: '/gestao-premio/espelhos', menuOrder: 118 },
  { code: 'prize.reports', moduleCode: 'prize', name: 'Relatorio e Auditoria', title: 'Relatorio e Auditoria', route: '/gestao-premio/relatorios', menuOrder: 119 },
  { code: 'prize.audit', moduleCode: 'prize', name: 'Auditoria do Premio', title: 'Auditoria do Premio', route: '/gestao-premio/auditoria', menuOrder: 119.1 },
  { code: 'prize.payroll', moduleCode: 'prize', name: 'Integracao com a Folha', title: 'Integracao com a Folha', route: '/gestao-premio/folha', menuOrder: 120 },
  { code: 'prize.integrations', moduleCode: 'prize', name: 'Integracoes Operacionais', title: 'Integracoes do Premio', route: '/gestao-premio/integracoes', menuOrder: 121 },
  { code: 'prize.connectors', moduleCode: 'prize', name: 'Integracoes do Premio', title: 'Integracoes do Premio', route: '/platform-admin?section=externalIntegrations&tab=prize', menuOrder: 199 },

  { code: 'service-desk.main', moduleCode: 'service-desk', name: 'Central de Atendimento', title: 'Central de Atendimento', route: '/central-atendimento', menuOrder: 105 },
  { code: 'service-desk.detail', moduleCode: 'service-desk', name: 'Detalhe do Chamado', title: 'Chamado de Atendimento', route: '/central-atendimento/detalhes/[id]', menuOrder: 105.1 },

  { code: 'settings.main', moduleCode: 'settings', name: 'Configuracoes', title: 'Configuracoes', route: '/settings', menuOrder: 200 },
  { code: 'settings.platform', moduleCode: 'settings', name: 'Plataforma', title: 'Plataforma', route: '/plataforma', menuOrder: 200.01 },
  { code: 'settings.company-selector', moduleCode: 'settings', name: 'Selecionar Empresa', title: 'Selecionar Empresa', route: '/selecionar-empresa', menuOrder: 200.02 },
  { code: 'settings.visibility', moduleCode: 'access-control', name: 'Matriz de Visibilidade', title: 'Visibilidade', route: '/settings/visibilidade', menuOrder: 200.1 },
  { code: 'settings.external-integrations', moduleCode: 'integrations', name: 'APIs Externas da Empresa', title: 'APIs Externas', route: '/settings/integracoes', menuOrder: 200.2 },
  { code: 'settings.privacy', moduleCode: 'settings', name: 'Privacidade e LGPD', title: 'Privacidade e LGPD', route: '/privacidade', menuOrder: 200.3 },
  { code: 'database-admin.main', moduleCode: 'database-admin', name: 'Administracao do Banco', title: 'Banco de Dados', route: '/settings/database', menuOrder: 201 },
  { code: 'database-admin.tables', moduleCode: 'database-admin', name: 'Tabelas', title: 'Tabelas do Banco', route: '/settings/database/tables', menuOrder: 201.1 },
  { code: 'database-admin.table-detail', moduleCode: 'database-admin', name: 'Detalhe da Tabela', title: 'Tabela do Banco', route: '/settings/database/tables/[table]', menuOrder: 201.11 },
  { code: 'database-admin.records', moduleCode: 'database-admin', name: 'Registros', title: 'Registros do Banco', route: '/settings/database/records', menuOrder: 201.2 },
  { code: 'database-admin.sql', moduleCode: 'database-admin', name: 'SQL', title: 'Consulta SQL', route: '/settings/database/sql', menuOrder: 201.3 },
  { code: 'database-admin.query-builder', moduleCode: 'database-admin', name: 'Construtor de Consultas', title: 'Construtor de Consultas', route: '/settings/database/query-builder', menuOrder: 201.4 },
  { code: 'database-admin.structure', moduleCode: 'database-admin', name: 'Estrutura', title: 'Estrutura do Banco', route: '/settings/database/structure', menuOrder: 201.5 },
  { code: 'database-admin.indexes', moduleCode: 'database-admin', name: 'Indices', title: 'Indices do Banco', route: '/settings/database/indexes', menuOrder: 201.6 },
  { code: 'database-admin.import-export', moduleCode: 'database-admin', name: 'Importacao e Exportacao', title: 'Importacao e Exportacao', route: '/settings/database/import-export', menuOrder: 201.7 },
  { code: 'database-admin.backups', moduleCode: 'database-admin', name: 'Backups', title: 'Backups', route: '/settings/database/backups', menuOrder: 201.8 },
  { code: 'database-admin.audit', moduleCode: 'database-admin', name: 'Auditoria do Banco', title: 'Auditoria do Banco', route: '/settings/database/audit', menuOrder: 201.9 },
  { code: 'database-admin.diagnostics', moduleCode: 'database-admin', name: 'Diagnosticos', title: 'Diagnosticos do Banco', route: '/settings/database/diagnostics', menuOrder: 201.91 },
  { code: 'database-admin.advanced', moduleCode: 'database-admin', name: 'Avancado', title: 'Administracao Avancada', route: '/settings/database/advanced', menuOrder: 201.92 },
  { code: 'portal-admin.main', moduleCode: 'portal-admin', name: 'Central do Portal', title: 'Central de Administracao do Portal', route: '/settings/portal', menuOrder: 202 },
  { code: 'integrations.main', moduleCode: 'integrations', name: 'Integracoes', title: 'Integracoes', route: '/integracoes', menuOrder: 203 },
  { code: 'audit.main', moduleCode: 'audit', name: 'Auditoria', title: 'Auditoria', route: '/audit', menuOrder: 204 },
  { code: 'directory.list', moduleCode: 'directory', name: 'Pessoas', title: 'Pessoas', route: '/pessoas', menuOrder: 905 },
  { code: 'auth.profile', moduleCode: 'auth', name: 'Meu Perfil', title: 'Meu Perfil', route: '/perfil', menuOrder: 905.1 },
  { code: 'directory.profile', moduleCode: 'directory', name: 'Perfil de Pessoa', title: 'Perfil', route: '/perfil/[id]', menuOrder: 905.2 },
  { code: 'help-center.main', moduleCode: 'help-center', name: 'Central de Ajuda', title: 'Central de Ajuda', route: '/ajuda', menuOrder: 906 },
  { code: 'forms.scan', moduleCode: 'forms', name: 'Leitor de Formularios', title: 'Leitor', route: '/scan', menuOrder: 906.1 },
  { code: 'treatments.detail', moduleCode: 'treatments', name: 'Detalhe da Tratativa', title: 'Tratativa', route: '/treatments/[id]', menuOrder: 906.2 },
  { code: 'dashboard.legacy', moduleCode: 'dashboard', name: 'Dashboard legado', title: 'Dashboard legado', route: '/dashboard', menuOrder: 900 },
];

export const CATALOG_FEATURES: CatalogFeature[] = [
  { code: 'communication.attachments', moduleCode: 'communication', name: 'Enviar anexos em mensagens' },
  { code: 'communication.mute', moduleCode: 'communication', name: 'Silenciar conversas' },
  { code: 'communication.pin', moduleCode: 'communication', name: 'Fixar conversas' },
  { code: 'communication.create', moduleCode: 'communication', name: 'Criar comunicados' },
  { code: 'communication.metrics', moduleCode: 'communication', name: 'Visualizar metricas de comunicacao' },
  { code: 'integrations.preference', moduleCode: 'integrations', name: 'Configurar preferencias de integracao' },
  { code: 'help-center.feedback', moduleCode: 'help-center', name: 'Registrar feedback de artigo' },
  { code: 'help-center.manage', moduleCode: 'help-center', name: 'Administrar artigos da ajuda', criticality: 'medium' },

  { code: 'indicators.create', moduleCode: 'indicators', name: 'Criar indicador' },
  { code: 'indicators.update', moduleCode: 'indicators', name: 'Editar indicador' },
  { code: 'indicators.delete', moduleCode: 'indicators', name: 'Excluir indicador', criticality: 'high' },
  { code: 'indicators.launch', moduleCode: 'indicators', name: 'Lancar resultado' },
  { code: 'indicators.import', moduleCode: 'indicators', name: 'Importar resultados' },
  { code: 'indicators.export', moduleCode: 'indicators', name: 'Exportar relatorio' },
  { code: 'indicators.history', moduleCode: 'indicators', name: 'Visualizar historico' },
  { code: 'actions.create', moduleCode: 'actions', name: 'Criar acao' },
  { code: 'actions.update', moduleCode: 'actions', name: 'Editar acao' },
  { code: 'actions.delete', moduleCode: 'actions', name: 'Excluir acao', criticality: 'high' },
  { code: 'actions.complete', moduleCode: 'actions', name: 'Finalizar acao' },
  { code: 'actions.reopen', moduleCode: 'actions', name: 'Reabrir acao' },
  { code: 'actions.export', moduleCode: 'actions', name: 'Exportar relatorio' },
  { code: 'risks.create', moduleCode: 'risks', name: 'Registrar risco' },
  { code: 'risks.update', moduleCode: 'risks', name: 'Editar risco' },
  { code: 'risks.delete', moduleCode: 'risks', name: 'Excluir risco', criticality: 'high' },
  { code: 'nonconformities.create', moduleCode: 'nonconformities', name: 'Registrar nao conformidade' },
  { code: 'nonconformities.update', moduleCode: 'nonconformities', name: 'Editar nao conformidade' },
  { code: 'nonconformities.delete', moduleCode: 'nonconformities', name: 'Excluir nao conformidade', criticality: 'high' },
  { code: 'documents.create', moduleCode: 'documents', name: 'Criar documento' },
  { code: 'documents.update', moduleCode: 'documents', name: 'Editar documento' },
  { code: 'documents.delete', moduleCode: 'documents', name: 'Excluir documento', criticality: 'high' },
  { code: 'audits.create', moduleCode: 'audits', name: 'Planejar auditoria' },
  { code: 'audits.update', moduleCode: 'audits', name: 'Executar auditoria e gerar NC' },
  { code: 'audits.delete', moduleCode: 'audits', name: 'Excluir auditoria', criticality: 'high' },
  { code: 'food-safety.manage', moduleCode: 'food-safety', name: 'Gerenciar processos, perigos e PCC' },
  { code: 'food-safety.intelligence', moduleCode: 'food-safety', name: 'Usar inteligencia em seguranca dos alimentos' },
  { code: 'automations.manage', moduleCode: 'automations', name: 'Criar e publicar fluxos', criticality: 'high' },
  { code: 'processes.create', moduleCode: 'processes', name: 'Mapear processo' },
  { code: 'processes.update', moduleCode: 'processes', name: 'Editar processos e etapas' },
  { code: 'processes.delete', moduleCode: 'processes', name: 'Excluir processo', criticality: 'high' },
  { code: 'asset-security.entry', moduleCode: 'asset-security', name: 'Registrar entrada' },
  { code: 'asset-security.exit', moduleCode: 'asset-security', name: 'Registrar saida' },
  { code: 'asset-security.authorize', moduleCode: 'asset-security', name: 'Gerenciar autorizacoes' },
  { code: 'asset-security.rounds', moduleCode: 'asset-security', name: 'Executar rondas' },
  { code: 'asset-security.offline', moduleCode: 'asset-security', name: 'Operacao offline', criticality: 'high' },
  { code: 'compensation.salary.individual', moduleCode: 'compensation', name: 'Visualizar salario individual', criticality: 'critical' },
  { code: 'compensation.movements.approve', moduleCode: 'compensation', name: 'Aprovar movimentacoes', criticality: 'high' },
  { code: 'compensation.export', moduleCode: 'compensation', name: 'Exportar dados de cargos e salarios', criticality: 'high' },
  { code: 'recruitment.requisitions', moduleCode: 'recruitment', name: 'Criar e aprovar requisicoes de vaga', criticality: 'high' },
  { code: 'recruitment.jobs', moduleCode: 'recruitment', name: 'Publicar vagas e administrar candidatos', criticality: 'high' },
  { code: 'recruitment.offers', moduleCode: 'recruitment', name: 'Aprovar propostas de contratacao', criticality: 'critical' },
  { code: 'recruitment.admission', moduleCode: 'recruitment', name: 'Converter pre-admissao em admissao', criticality: 'critical' },
  { code: 'recruitment.lgpd', moduleCode: 'recruitment', name: 'Administrar privacidade de candidatos', criticality: 'high' },
  { code: 'personnel.employees', moduleCode: 'personnel', name: 'Administrar colaboradores e prontuarios', criticality: 'critical' },
  { code: 'personnel.time-clock', moduleCode: 'personnel', name: 'Administrar jornadas, ponto e fechamentos', criticality: 'critical' },
  { code: 'personnel.facial-clock', moduleCode: 'personnel', name: 'Registrar ponto por reconhecimento facial', criticality: 'high' },
  { code: 'personnel.kiosk', moduleCode: 'personnel', name: 'Operar terminal Totem exclusivo', criticality: 'high' },
  { code: 'personnel.vacations', moduleCode: 'personnel', name: 'Administrar ferias e afastamentos', criticality: 'high' },
  { code: 'personnel.exports', moduleCode: 'personnel', name: 'Exportar ponto e dados para contabilidade', criticality: 'critical' },
  { code: 'payroll.calculate', moduleCode: 'payroll', name: 'Calcular e fechar folha de pagamento', criticality: 'critical' },
  { code: 'payroll.esocial', moduleCode: 'payroll', name: 'Transmitir e conciliar eventos do eSocial', criticality: 'critical' },
  { code: 'payroll.dataprev', moduleCode: 'payroll', name: 'Integrar obrigacoes com Dataprev', criticality: 'critical' },
  { code: 'payroll.accounting-export', moduleCode: 'payroll', name: 'Exportar arquivos para contabilidade externa', criticality: 'critical' },
  { code: 'procurement.request', moduleCode: 'procurement', name: 'Criar requisicoes de compra' },
  { code: 'procurement.buy', moduleCode: 'procurement', name: 'Administrar cotacoes e pedidos', criticality: 'high' },
  { code: 'procurement.approve', moduleCode: 'procurement', name: 'Aprovar compras por alcada', criticality: 'high' },
  { code: 'inventory.operate', moduleCode: 'inventory', name: 'Operar recebimentos, retiradas e transferencias', criticality: 'high' },
  { code: 'inventory.adjust', moduleCode: 'inventory', name: 'Ajustar saldos de estoque', criticality: 'critical' },
  { code: 'forms.create', moduleCode: 'forms', name: 'Criar formulario/checklist' },
  { code: 'forms.update', moduleCode: 'forms', name: 'Editar campos e registrar preenchimento' },
  { code: 'forms.delete', moduleCode: 'forms', name: 'Excluir formulario', criticality: 'high' },
  { code: 'meetings.invite', moduleCode: 'meetings', name: 'Enviar convite ICS' },
  { code: 'reports.export', moduleCode: 'reports', name: 'Exportar relatorios' },
  { code: 'prize.admin', moduleCode: 'prize', name: 'Administrar configuracoes do premio', criticality: 'high' },
  { code: 'prize.connectors', moduleCode: 'prize', name: 'Gerenciar conectores do premio', criticality: 'high' },
  { code: 'prize.reports', moduleCode: 'prize', name: 'Visualizar relatorios do premio' },
];
