'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { api } from '@/lib/api';

type Measurement = { id:string; number:string; purchaseOrderId:string; status:string; periodStart:string; periodEnd:string; items:any[] };
type Count = { id:string; number:string; warehouseId:string; status:string; items:Array<{id:string;itemId:string;expectedQuantity:string;countedQuantity?:string}> };
type Options = { warehouses:Array<{id:string;name:string}>; users:Array<{id:string;name:string}> };
export function SuppliesAdvanced() {
 const qc=useQueryClient(); const [qr,setQr]=useState(''); const [qrResult,setQrResult]=useState<any>();
 const measurements=useQuery<Measurement[]>({queryKey:['supplies','measurements'],queryFn:()=>api('/supplies-advanced/measurements')});
 const quotations=useQuery<any[]>({queryKey:['supplies','quotations'],queryFn:()=>api('/procurement/quotations')});
 const invoices=useQuery<any[]>({queryKey:['supplies','invoices'],queryFn:()=>api('/procurement/invoices')});
 const counts=useQuery<Count[]>({queryKey:['supplies','counts'],queryFn:()=>api('/supplies-advanced/inventory-counts')});
 const abc=useQuery<any[]>({queryKey:['supplies','abc'],queryFn:()=>api('/supplies-advanced/abc-curve')});
 const policies=useQuery<any[]>({queryKey:['supplies','policies'],queryFn:()=>api('/supplies-advanced/withdrawal-policies')});
 const options=useQuery<Options>({queryKey:['supplies','options'],queryFn:()=>api('/procurement/options')});
 const write=useMutation({mutationFn:({path,json={}}:{path:string;json?:any})=>api(path,{method:'POST',json}),onSuccess:()=>{toast.success('Operação concluída');void qc.invalidateQueries({queryKey:['supplies']});},onError:(e:Error)=>toast.error(e.message)});
 const act=(path:string,json?:any)=>write.mutate({path,json});
 return <Tabs defaultValue="quotes"><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="quotes">Cotações e NFs</TabsTrigger><TabsTrigger value="services">Serviços</TabsTrigger><TabsTrigger value="counts">Inventário</TabsTrigger><TabsTrigger value="abc">Curva ABC</TabsTrigger><TabsTrigger value="qr">QR</TabsTrigger><TabsTrigger value="policies">Políticas</TabsTrigger></TabsList>
 <TabsContent value="quotes" className="space-y-3"><QuotationForm onSave={v=>act('/procurement/quotations',v)}/>{quotations.data?.map(q=><Row key={q.id} title={q.number} detail={`${q.requisition?.number??'Requisição'} · ${q.supplierQuotes?.length??0} proposta(s)`} status={q.status}>{q.status==='OPEN'&&<Button size="sm" onClick={()=>{const supplierQuoteId=prompt('ID da proposta vencedora');const justification=prompt('Justificativa da escolha');if(supplierQuoteId&&justification)act(`/procurement/quotations/${q.id}/award`,{supplierQuoteId,justification});}}>Escolher vencedor</Button>}</Row>)}<h3 className="pt-3 font-semibold">Notas fiscais</h3>{invoices.data?.map(n=><Row key={n.id} title={`NF ${n.invoiceNumber}`} detail={`${n.supplier?.tradeName??n.supplier?.legalName??''} · ${money(n.totalAmount)}`} status={n.status}>{n.status==='POSTED'&&<Button size="sm" onClick={()=>act(`/procurement/invoices/${n.id}/verify`)}>Conferir</Button>}</Row>)}</TabsContent>
 <TabsContent value="services" className="space-y-3"><MeasurementForm options={options.data} onSave={(v)=>act('/supplies-advanced/measurements',v)}/>{measurements.data?.map(m=><Row key={m.id} title={m.number} detail={`${m.items.length} item(ns) · ${date(m.periodStart)} a ${date(m.periodEnd)}`} status={m.status}>{['DRAFT','CONTESTED'].includes(m.status)&&<Button size="sm" onClick={()=>act(`/supplies-advanced/measurements/${m.id}/submit`)}>Enviar</Button>}{m.status==='SUBMITTED'&&<><Button size="sm" onClick={()=>act(`/supplies-advanced/measurements/${m.id}/approve`)}>Aprovar</Button><Button size="sm" variant="outline" onClick={()=>{const reason=prompt('Motivo');if(reason)act(`/supplies-advanced/measurements/${m.id}/contest`,{reason});}}>Contestar</Button></>}{m.status==='APPROVED'&&<Button size="sm" onClick={()=>{const invoiceNumber=prompt('Número da NF');if(invoiceNumber)act('/supplies-advanced/invoices/service',{serviceMeasurementId:m.id,invoiceNumber,issuedAt:new Date().toISOString()});}}>Lançar NF</Button>}</Row>)}</TabsContent>
 <TabsContent value="counts" className="space-y-3"><CountForm options={options.data} onSave={v=>act('/supplies-advanced/inventory-counts',v)}/>{counts.data?.map(c=><Row key={c.id} title={c.number} detail={`${c.items.length} item(ns)`} status={c.status}>{c.status==='DRAFT'&&<Button size="sm" onClick={()=>act(`/supplies-advanced/inventory-counts/${c.id}/start`)}>Iniciar</Button>}{c.status==='COUNTING'&&<Button size="sm" onClick={()=>act(`/supplies-advanced/inventory-counts/${c.id}/record`,{items:c.items.map(i=>({inventoryCountItemId:i.id,countedQuantity:prompt(`Contagem ${i.itemId.slice(0,8)}`,i.expectedQuantity)??i.expectedQuantity}))})}>Registrar</Button>}{c.status==='COUNTING'&&c.items.every(i=>i.countedQuantity!=null)&&<Button size="sm" variant="outline" onClick={()=>act(`/supplies-advanced/inventory-counts/${c.id}/complete`,{idempotencyKey:crypto.randomUUID()})}>Concluir</Button>}</Row>)}</TabsContent>
 <TabsContent value="abc" className="space-y-2">{abc.data?.map((r,i)=><Row key={i} title={`${r.item.code} · ${r.item.name}`} detail={`${r.warehouse.name} · acumulado ${Number(r.cumulativePercentage).toFixed(1)}%`} status={`Classe ${r.abcClass}`}><b>{money(r.stockValue)}</b></Row>)}</TabsContent>
 <TabsContent value="qr"><Card><CardContent className="space-y-3 p-4"><div className="flex gap-2"><Input value={qr} onChange={e=>setQr(e.target.value)} placeholder="Token do QR"/><Button onClick={async()=>{try{setQrResult(await api(`/supplies-advanced/qr/${encodeURIComponent(qr)}`));}catch(e:any){toast.error(e.message)}}}>Consultar</Button></div>{qrResult&&<div><b>{qrResult.item.code} · {qrResult.item.name}</b><div>{qrResult.balances.map((b:any)=>`${b.warehouse.name}: ${b.quantity}`).join(' · ')}</div></div>}</CardContent></Card></TabsContent>
 <TabsContent value="policies" className="space-y-3"><PolicyForm onSave={v=>act('/supplies-advanced/withdrawal-policies',v)}/>{policies.data?.map(p=><Row key={p.id} title={p.name} detail={`A partir de ${money(p.minimumAmount)} · ${p.approverRole??'Aprovador nominal'}`} status={p.active?'Ativa':'Inativa'}/>)}</TabsContent></Tabs>;
}
function MeasurementForm({options,onSave}:{options?:Options;onSave:(v:any)=>void}){const [v,setV]=useState({purchaseOrderId:'',purchaseOrderItemId:'',fiscalUserId:'',quantity:'1'});return <Card><CardContent className="grid gap-2 p-4 md:grid-cols-5"><Input placeholder="ID do pedido" value={v.purchaseOrderId} onChange={e=>setV({...v,purchaseOrderId:e.target.value})}/><Input placeholder="ID do item" value={v.purchaseOrderItemId} onChange={e=>setV({...v,purchaseOrderItemId:e.target.value})}/><select className="h-10 rounded border bg-background px-2" value={v.fiscalUserId} onChange={e=>setV({...v,fiscalUserId:e.target.value})}><option value="">Fiscal</option>{options?.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><Input type="number" value={v.quantity} onChange={e=>setV({...v,quantity:e.target.value})}/><Button onClick={()=>onSave({...v,periodStart:new Date().toISOString(),periodEnd:new Date().toISOString(),items:[{purchaseOrderItemId:v.purchaseOrderItemId,quantity:v.quantity}]})}>Nova medição</Button></CardContent></Card>}
function QuotationForm({onSave}:{onSave:(v:any)=>void}){const [requisitionId,setId]=useState('');return <Card><CardContent className="flex gap-2 p-4"><Input placeholder="ID da requisição em triagem" value={requisitionId} onChange={e=>setId(e.target.value)}/><Button disabled={!requisitionId} onClick={()=>onSave({requisitionId})}>Abrir cotação</Button></CardContent></Card>}
function CountForm({options,onSave}:{options?:Options;onSave:(v:any)=>void}){const [warehouseId,setId]=useState('');return <Card><CardContent className="flex gap-2 p-4"><select className="h-10 min-w-64 rounded border bg-background px-2" value={warehouseId} onChange={e=>setId(e.target.value)}><option value="">Almoxarifado</option>{options?.warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><Button disabled={!warehouseId} onClick={()=>onSave({warehouseId})}>Abrir inventário</Button></CardContent></Card>}
function PolicyForm({onSave}:{onSave:(v:any)=>void}){const [name,setName]=useState('');const [minimumAmount,setMin]=useState('0');return <Card><CardContent className="grid gap-2 p-4 md:grid-cols-3"><Input placeholder="Nome da política" value={name} onChange={e=>setName(e.target.value)}/><Input type="number" value={minimumAmount} onChange={e=>setMin(e.target.value)}/><Button disabled={name.length<2} onClick={()=>onSave({name,minimumAmount,approverRole:'MANAGER'})}>Criar política</Button></CardContent></Card>}
function Row({title,detail,status,children}:{title:string;detail:string;status:string;children?:React.ReactNode}){return <Card><CardContent className="flex flex-wrap items-center justify-between gap-2 p-4"><div><b>{title}</b><div className="text-xs text-muted-foreground">{detail}</div></div><div className="flex items-center gap-2"><Badge variant="outline">{status}</Badge>{children}</div></CardContent></Card>}
const date=(v:string)=>new Date(v).toLocaleDateString('pt-BR');const money=(v:any)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));
