'use client';

import { useEffect, useState, type ReactNode } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { NativeSelect } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import type { MaterialWithdrawal, ProcurementOptions, PurchaseOrder, PurchaseRequisition } from './supplies-types';

type Submit = (payload: any) => void;

export function RequisitionDialog({ open, options, loading, onOpenChange, onSubmit }: CommonProps & { options?: ProcurementOptions; onSubmit: Submit }) {
  const [form, setForm] = useState<any>({ title: '', warehouseId: '', orgNodeId: '', urgency: 'NORMAL', justification: '', neededAt: '', submit: true, items: [{ itemId: '', quantity: '1', estimatedUnitCost: '' }] });
  useEffect(() => { if (open) setForm({ title: '', warehouseId: options?.warehouses[0]?.id ?? '', orgNodeId: '', urgency: 'NORMAL', justification: '', neededAt: '', submit: true, items: [{ itemId: '', quantity: '1', estimatedUnitCost: '' }] }); }, [open, options]);
  const updateLine = (index: number, patch: any) => setForm((current: any) => ({ ...current, items: current.items.map((line: any, i: number) => i === index ? { ...line, ...patch } : line) }));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Nova requisição de compra</DialogTitle><DialogDescription>Escolha o almoxarifado de destino. O comprador verá a requisição na fila do Meu Dia.</DialogDescription></DialogHeader>
    <div className="grid gap-3 md:grid-cols-2">
      <Field label="Título"><Input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Ex.: Reposição de EPIs" /></Field>
      <Field label="Urgência"><NativeSelect value={form.urgency} onChange={(e) => setForm({ ...form, urgency: e.target.value })}><option value="LOW">Baixa</option><option value="NORMAL">Normal</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></NativeSelect></Field>
      <Field label="Almoxarifado de destino"><NativeSelect value={form.warehouseId} onChange={(e) => setForm({ ...form, warehouseId: e.target.value })}><option value="">Selecione</option>{options?.warehouses.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</NativeSelect></Field>
      <Field label="Centro de custo / área"><NativeSelect value={form.orgNodeId} onChange={(e) => setForm({ ...form, orgNodeId: e.target.value })}><option value="">Não informado</option>{options?.orgNodes.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</NativeSelect></Field>
      <Field label="Necessário até"><Input type="date" value={form.neededAt} onChange={(e) => setForm({ ...form, neededAt: e.target.value })} /></Field>
      <Field label="Envio"><NativeSelect value={form.submit ? 'submit' : 'draft'} onChange={(e) => setForm({ ...form, submit: e.target.value === 'submit' })}><option value="submit">Enviar para compras</option><option value="draft">Salvar rascunho</option></NativeSelect></Field>
    </div>
    <Field label="Justificativa"><Textarea value={form.justification} onChange={(e) => setForm({ ...form, justification: e.target.value })} placeholder="Explique a necessidade e o impacto operacional" /></Field>
    <div className="space-y-2"><div className="flex items-center justify-between"><Label>Itens</Label><Button type="button" size="sm" variant="outline" onClick={() => setForm({ ...form, items: [...form.items, { itemId: '', quantity: '1', estimatedUnitCost: '' }] })}><Plus className="mr-1 h-4 w-4" />Adicionar item</Button></div>
      {form.items.map((line: any, index: number) => <div key={index} className="grid gap-2 rounded-md border p-2 md:grid-cols-[1fr_120px_140px_36px]">
        <NativeSelect aria-label={`Item ${index + 1}`} value={line.itemId} onChange={(e) => updateLine(index, { itemId: e.target.value })}><option value="">Selecione o item</option>{options?.items.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name} ({item.unit})</option>)}</NativeSelect>
        <Input aria-label={`Quantidade ${index + 1}`} type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={(e) => updateLine(index, { quantity: e.target.value })} />
        <Input aria-label={`Custo estimado ${index + 1}`} type="number" min="0" step="0.01" value={line.estimatedUnitCost} placeholder="Custo estimado" onChange={(e) => updateLine(index, { estimatedUnitCost: e.target.value })} />
        <Button type="button" size="icon" variant="ghost" disabled={form.items.length === 1} onClick={() => setForm({ ...form, items: form.items.filter((_: any, i: number) => i !== index) })}><Trash2 className="h-4 w-4" /></Button>
      </div>)}
    </div>
    <DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={loading || !form.title || !form.warehouseId || !form.justification || form.items.some((line: any) => !line.itemId)} onClick={() => onSubmit(cleanPayload(form))}>{loading ? 'Salvando...' : form.submit ? 'Enviar requisição' : 'Salvar rascunho'}</Button></DialogFooter>
  </DialogContent></Dialog>;
}

export function OrderDialog({ open, requisition, options, loading, onOpenChange, onSubmit }: CommonProps & { requisition: PurchaseRequisition | null; options?: ProcurementOptions; onSubmit: Submit }) {
  const [form, setForm] = useState<any>({ supplierId: '', paymentTerms: '', expectedDeliveryAt: '', freightAmount: '0', discountAmount: '0', notes: '', items: [] });
  useEffect(() => { if (open && requisition) setForm({ supplierId: options?.suppliers[0]?.id ?? '', paymentTerms: '', expectedDeliveryAt: '', freightAmount: '0', discountAmount: '0', notes: '', items: requisition.items.filter((line) => line.item.kind === 'MATERIAL' && Number(line.requestedQuantity) > Number(line.orderedQuantity)).map((line) => ({ requisitionItemId: line.id, label: `${line.item.code} · ${line.item.name}`, quantity: String(Number(line.requestedQuantity) - Number(line.orderedQuantity)), unitPrice: String(line.estimatedUnitCost ?? line.item.averageCost ?? 0) })) }); }, [open, requisition, options]);
  const update = (index: number, patch: any) => setForm((current: any) => ({ ...current, items: current.items.map((line: any, i: number) => i === index ? { ...line, ...patch } : line) }));
  const total = form.items.reduce((sum: number, line: any) => sum + Number(line.quantity || 0) * Number(line.unitPrice || 0), 0) + Number(form.freightAmount || 0) - Number(form.discountAmount || 0);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Gerar pedido de compra</DialogTitle><DialogDescription>{requisition?.number} · o pedido será criado em rascunho e depois seguirá para a alçada.</DialogDescription></DialogHeader>
    <div className="grid gap-3 md:grid-cols-2"><Field label="Fornecedor"><NativeSelect value={form.supplierId} onChange={(e) => { const supplier = options?.suppliers.find((row) => row.id === e.target.value); setForm({ ...form, supplierId: e.target.value, paymentTerms: supplier?.paymentTerms ?? form.paymentTerms }); }}><option value="">Selecione</option>{options?.suppliers.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.tradeName ?? row.legalName}</option>)}</NativeSelect></Field>
      <Field label="Previsão de entrega"><Input type="date" value={form.expectedDeliveryAt} onChange={(e) => setForm({ ...form, expectedDeliveryAt: e.target.value })} /></Field>
      <Field label="Condição de pagamento"><Input value={form.paymentTerms} onChange={(e) => setForm({ ...form, paymentTerms: e.target.value })} /></Field>
      <div className="grid grid-cols-2 gap-2"><Field label="Frete"><Input type="number" min="0" step="0.01" value={form.freightAmount} onChange={(e) => setForm({ ...form, freightAmount: e.target.value })} /></Field><Field label="Desconto"><Input type="number" min="0" step="0.01" value={form.discountAmount} onChange={(e) => setForm({ ...form, discountAmount: e.target.value })} /></Field></div>
    </div>
    <div className="space-y-2">{form.items.map((line: any, index: number) => <div key={line.requisitionItemId} className="grid items-end gap-2 rounded-md border p-2 md:grid-cols-[1fr_140px_160px]"><div className="pb-2 text-sm font-medium">{line.label}</div><Field label="Quantidade"><Input type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={(e) => update(index, { quantity: e.target.value })} /></Field><Field label="Preço unitário"><Input type="number" min="0" step="0.01" value={line.unitPrice} onChange={(e) => update(index, { unitPrice: e.target.value })} /></Field></div>)}</div>
    <Field label="Observações"><Textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field><div className="text-right text-lg font-semibold">Total: {money(total)}</div>
    <DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={loading || !form.supplierId || !form.items.length} onClick={() => onSubmit(cleanPayload({ ...form, requisitionId: requisition?.id, items: form.items.map(({ requisitionItemId, quantity, unitPrice }: any) => ({ requisitionItemId, quantity, unitPrice })) }))}>{loading ? 'Gerando...' : 'Gerar pedido'}</Button></DialogFooter>
  </DialogContent></Dialog>;
}

export function ReceiveDialog({ open, order, loading, onOpenChange, onSubmit }: CommonProps & { order: PurchaseOrder | null; onSubmit: Submit }) {
  const [form, setForm] = useState<any>({ deliveryNote: '', notes: '', items: [] });
  useEffect(() => { if (open && order) setForm({ deliveryNote: '', notes: '', items: order.items.filter((line) => line.kindSnapshot === 'MATERIAL' && Number(line.receivedQuantity) < Number(line.orderedQuantity)).map((line) => ({ purchaseOrderItemId: line.id, label: `${line.item.code} · ${line.item.name}`, quantity: String(Number(line.orderedQuantity) - Number(line.receivedQuantity)), unit: line.unit })) }); }, [open, order]);
  const update = (index: number, quantity: string) => setForm((current: any) => ({ ...current, items: current.items.map((line: any, i: number) => i === index ? { ...line, quantity } : line) }));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Receber material</DialogTitle><DialogDescription>{order?.number} · a confirmação gera entrada e kardex no almoxarifado {order?.warehouse.name}.</DialogDescription></DialogHeader>
    <Field label="Romaneio / documento de entrega"><Input value={form.deliveryNote} onChange={(e) => setForm({ ...form, deliveryNote: e.target.value })} /></Field>
    <div className="space-y-2">{form.items.map((line: any, index: number) => <div key={line.purchaseOrderItemId} className="grid items-center gap-2 rounded-md border p-2 md:grid-cols-[1fr_160px]"><span className="text-sm font-medium">{line.label}</span><Input aria-label={`Quantidade recebida ${index + 1}`} type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={(e) => update(index, e.target.value)} /></div>)}</div>
    <Field label="Observações"><Textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field>
    <DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={loading || !form.items.length} onClick={() => onSubmit(cleanPayload({ ...form, idempotencyKey: operationKey('receipt'), items: form.items.map(({ purchaseOrderItemId, quantity }: any) => ({ purchaseOrderItemId, quantity })) }))}>{loading ? 'Processando...' : 'Confirmar recebimento'}</Button></DialogFooter>
  </DialogContent></Dialog>;
}

export function WithdrawalDialog({ open, options, loading, onOpenChange, onSubmit }: CommonProps & { options?: ProcurementOptions; onSubmit: Submit }) {
  const [form, setForm] = useState<any>({ warehouseId: '', orgNodeId: '', justification: '', neededAt: '', items: [{ itemId: '', quantity: '1' }] });
  useEffect(() => { if (open) setForm({ warehouseId: options?.warehouses[0]?.id ?? '', orgNodeId: '', justification: '', neededAt: '', items: [{ itemId: '', quantity: '1' }] }); }, [open, options]);
  const update = (index: number, patch: any) => setForm((current: any) => ({ ...current, items: current.items.map((line: any, i: number) => i === index ? { ...line, ...patch } : line) }));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Solicitar retirada</DialogTitle><DialogDescription>O almoxarife atenderá a solicitação e a baixa será registrada no kardex.</DialogDescription></DialogHeader>
    <div className="grid gap-3 md:grid-cols-2"><Field label="Almoxarifado"><NativeSelect value={form.warehouseId} onChange={(e) => setForm({ ...form, warehouseId: e.target.value })}><option value="">Selecione</option>{options?.warehouses.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</NativeSelect></Field><Field label="Área / centro de custo"><NativeSelect value={form.orgNodeId} onChange={(e) => setForm({ ...form, orgNodeId: e.target.value })}><option value="">Não informado</option>{options?.orgNodes.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</NativeSelect></Field></div>
    <Field label="Justificativa"><Textarea value={form.justification} onChange={(e) => setForm({ ...form, justification: e.target.value })} /></Field>
    <div className="space-y-2">{form.items.map((line: any, index: number) => <div key={index} className="grid gap-2 md:grid-cols-[1fr_130px_36px]"><NativeSelect value={line.itemId} onChange={(e) => update(index, { itemId: e.target.value })}><option value="">Selecione o material</option>{options?.items.filter((item) => item.kind === 'MATERIAL').map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</NativeSelect><Input type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={(e) => update(index, { quantity: e.target.value })} /><Button type="button" size="icon" variant="ghost" disabled={form.items.length === 1} onClick={() => setForm({ ...form, items: form.items.filter((_: any, i: number) => i !== index) })}><Trash2 className="h-4 w-4" /></Button></div>)}</div>
    <Button type="button" size="sm" variant="outline" onClick={() => setForm({ ...form, items: [...form.items, { itemId: '', quantity: '1' }] })}><Plus className="mr-1 h-4 w-4" />Adicionar material</Button>
    <DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={loading || !form.warehouseId || !form.justification || form.items.some((line: any) => !line.itemId)} onClick={() => onSubmit(cleanPayload(form))}>{loading ? 'Salvando...' : 'Solicitar retirada'}</Button></DialogFooter>
  </DialogContent></Dialog>;
}

export function FulfillDialog({ open, withdrawal, loading, onOpenChange, onSubmit }: CommonProps & { withdrawal: MaterialWithdrawal | null; onSubmit: Submit }) {
  const [items, setItems] = useState<any[]>([]);
  useEffect(() => { if (open && withdrawal) setItems(withdrawal.items.filter((line) => Number(line.fulfilledQuantity) < Number(line.approvedQuantity ?? line.requestedQuantity)).map((line) => ({ withdrawalItemId: line.id, label: `${line.item.code} · ${line.item.name}`, quantity: String(Number(line.approvedQuantity ?? line.requestedQuantity) - Number(line.fulfilledQuantity)), unit: line.item.unit }))); }, [open, withdrawal]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Atender retirada</DialogTitle><DialogDescription>{withdrawal?.number} · cada quantidade confirmada gera baixa no kardex.</DialogDescription></DialogHeader>
    <div className="space-y-2">{items.map((line, index) => <div key={line.withdrawalItemId} className="grid items-center gap-2 rounded-md border p-2 sm:grid-cols-[1fr_140px]"><span className="text-sm font-medium">{line.label}</span><Input type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={(e) => setItems(items.map((row, i) => i === index ? { ...row, quantity: e.target.value } : row))} /></div>)}</div>
    <DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={loading || !items.length} onClick={() => onSubmit({ idempotencyKey: operationKey('withdrawal'), items: items.map(({ withdrawalItemId, quantity }) => ({ withdrawalItemId, quantity })) })}>{loading ? 'Processando...' : 'Confirmar baixa'}</Button></DialogFooter>
  </DialogContent></Dialog>;
}

export function StockOperationDialog({ open, mode, options, loading, onOpenChange, onSubmit }: CommonProps & { mode: 'adjust' | 'transfer'; options?: ProcurementOptions; onSubmit: Submit }) {
  const [form, setForm] = useState<any>({ warehouseId: '', sourceWarehouseId: '', destinationWarehouseId: '', itemId: '', quantityDelta: '', quantity: '', unitCost: '', reason: '', reference: '' });
  useEffect(() => { if (open) setForm({ warehouseId: options?.warehouses[0]?.id ?? '', sourceWarehouseId: options?.warehouses[0]?.id ?? '', destinationWarehouseId: options?.warehouses[1]?.id ?? '', itemId: '', quantityDelta: '', quantity: '', unitCost: '', reason: '', reference: '' }); }, [open, options]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{mode === 'adjust' ? 'Ajustar saldo' : 'Transferir material'}</DialogTitle><DialogDescription>{mode === 'adjust' ? 'Use valor positivo para entrada e negativo para redução. O motivo fica no kardex.' : 'A saída e a entrada são gravadas juntas, com o mesmo custo médio.'}</DialogDescription></DialogHeader>
    {mode === 'adjust' ? <Field label="Almoxarifado"><WarehouseSelect value={form.warehouseId} options={options} onChange={(value) => setForm({ ...form, warehouseId: value })} /></Field> : <div className="grid gap-3 sm:grid-cols-2"><Field label="Origem"><WarehouseSelect value={form.sourceWarehouseId} options={options} onChange={(value) => setForm({ ...form, sourceWarehouseId: value })} /></Field><Field label="Destino"><WarehouseSelect value={form.destinationWarehouseId} options={options} onChange={(value) => setForm({ ...form, destinationWarehouseId: value })} /></Field></div>}
    <Field label="Material"><NativeSelect value={form.itemId} onChange={(e) => setForm({ ...form, itemId: e.target.value })}><option value="">Selecione</option>{options?.items.filter((item) => item.kind === 'MATERIAL').map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</NativeSelect></Field>
    <div className="grid gap-3 sm:grid-cols-2"><Field label={mode === 'adjust' ? 'Variação de quantidade' : 'Quantidade'}><Input type="number" step="0.0001" value={mode === 'adjust' ? form.quantityDelta : form.quantity} onChange={(e) => setForm({ ...form, [mode === 'adjust' ? 'quantityDelta' : 'quantity']: e.target.value })} /></Field>{mode === 'adjust' && <Field label="Custo unitário (entradas)"><Input type="number" min="0" step="0.01" value={form.unitCost} onChange={(e) => setForm({ ...form, unitCost: e.target.value })} /></Field>}</div>
    <Field label="Motivo"><Textarea value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></Field><Field label="Referência"><Input value={form.reference} onChange={(e) => setForm({ ...form, reference: e.target.value })} /></Field>
    <DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={loading || !form.itemId || !form.reason} onClick={() => onSubmit(cleanPayload(mode === 'adjust'
      ? { warehouseId: form.warehouseId, itemId: form.itemId, quantityDelta: form.quantityDelta, ...(form.unitCost !== '' ? { unitCost: form.unitCost } : {}), reason: form.reason, reference: form.reference, idempotencyKey: operationKey(mode) }
      : { sourceWarehouseId: form.sourceWarehouseId, destinationWarehouseId: form.destinationWarehouseId, itemId: form.itemId, quantity: form.quantity, reason: form.reason, reference: form.reference, idempotencyKey: operationKey(mode) }))}>{loading ? 'Processando...' : mode === 'adjust' ? 'Registrar ajuste' : 'Transferir'}</Button></DialogFooter>
  </DialogContent></Dialog>;
}

export type RegistrationKind = 'warehouse' | 'item' | 'supplier' | 'rule';
export function RegistrationDialog({ open, kind, options, loading, onOpenChange, onSubmit }: CommonProps & { kind: RegistrationKind; options?: ProcurementOptions; onSubmit: Submit }) {
  const [form, setForm] = useState<any>({});
  useEffect(() => { if (!open) return; setForm(kind === 'warehouse' ? { code: '', name: '', orgNodeId: '', managerUserId: '', address: '', allowNegative: false } : kind === 'item' ? { code: '', name: '', kind: 'MATERIAL', unit: 'UN', groupName: '', minimumStock: '', maximumStock: '' } : kind === 'supplier' ? { code: '', legalName: '', tradeName: '', documentNumber: '', email: '', phone: '', paymentTerms: '' } : { name: '', level: 1, minimumAmount: '0', maximumAmount: '', approverUserId: '', approverRole: '' }); }, [open, kind]);
  const titles = { warehouse: 'Novo almoxarifado', item: 'Novo item', supplier: 'Novo fornecedor', rule: 'Nova alçada' };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{titles[kind]}</DialogTitle><DialogDescription>Cadastro corporativo de Suprimentos.</DialogDescription></DialogHeader>
    {kind === 'warehouse' && <><div className="grid gap-3 sm:grid-cols-2"><Field label="Código"><Input value={form.code ?? ''} onChange={(e) => setForm({ ...form, code: e.target.value })} /></Field><Field label="Nome"><Input value={form.name ?? ''} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field></div><Field label="Área"><NativeSelect value={form.orgNodeId ?? ''} onChange={(e) => setForm({ ...form, orgNodeId: e.target.value })}><option value="">Não informada</option>{options?.orgNodes.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</NativeSelect></Field><Field label="Responsável"><NativeSelect value={form.managerUserId ?? ''} onChange={(e) => setForm({ ...form, managerUserId: e.target.value })}><option value="">Não informado</option>{options?.users.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</NativeSelect></Field><Field label="Endereço / localização"><Input value={form.address ?? ''} onChange={(e) => setForm({ ...form, address: e.target.value })} /></Field></>}
    {kind === 'item' && <><div className="grid gap-3 sm:grid-cols-2"><Field label="Código"><Input value={form.code ?? ''} onChange={(e) => setForm({ ...form, code: e.target.value })} /></Field><Field label="Tipo"><NativeSelect value={form.kind ?? 'MATERIAL'} onChange={(e) => setForm({ ...form, kind: e.target.value })}><option value="MATERIAL">Material</option><option value="SERVICE">Serviço</option></NativeSelect></Field></div><Field label="Nome"><Input value={form.name ?? ''} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Unidade"><Input value={form.unit ?? ''} onChange={(e) => setForm({ ...form, unit: e.target.value })} /></Field><Field label="Grupo"><Input value={form.groupName ?? ''} onChange={(e) => setForm({ ...form, groupName: e.target.value })} /></Field><Field label="Estoque mínimo"><Input type="number" min="0" value={form.minimumStock ?? ''} onChange={(e) => setForm({ ...form, minimumStock: e.target.value })} /></Field><Field label="Estoque máximo"><Input type="number" min="0" value={form.maximumStock ?? ''} onChange={(e) => setForm({ ...form, maximumStock: e.target.value })} /></Field></div></>}
    {kind === 'supplier' && <><div className="grid gap-3 sm:grid-cols-2"><Field label="Código"><Input value={form.code ?? ''} onChange={(e) => setForm({ ...form, code: e.target.value })} /></Field><Field label="CNPJ/CPF"><Input value={form.documentNumber ?? ''} onChange={(e) => setForm({ ...form, documentNumber: e.target.value })} /></Field></div><Field label="Razão social"><Input value={form.legalName ?? ''} onChange={(e) => setForm({ ...form, legalName: e.target.value })} /></Field><Field label="Nome fantasia"><Input value={form.tradeName ?? ''} onChange={(e) => setForm({ ...form, tradeName: e.target.value })} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="E-mail"><Input type="email" value={form.email ?? ''} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="Telefone"><Input value={form.phone ?? ''} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></Field></div><Field label="Condição de pagamento"><Input value={form.paymentTerms ?? ''} onChange={(e) => setForm({ ...form, paymentTerms: e.target.value })} /></Field></>}
    {kind === 'rule' && <><Field label="Nome"><Input value={form.name ?? ''} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><div className="grid gap-3 sm:grid-cols-3"><Field label="Nível"><Input type="number" min="1" value={form.level ?? 1} onChange={(e) => setForm({ ...form, level: Number(e.target.value) })} /></Field><Field label="Valor mínimo"><Input type="number" min="0" value={form.minimumAmount ?? ''} onChange={(e) => setForm({ ...form, minimumAmount: e.target.value })} /></Field><Field label="Valor máximo"><Input type="number" min="0" value={form.maximumAmount ?? ''} onChange={(e) => setForm({ ...form, maximumAmount: e.target.value })} /></Field></div><Field label="Aprovador específico"><NativeSelect value={form.approverUserId ?? ''} onChange={(e) => setForm({ ...form, approverUserId: e.target.value, approverRole: e.target.value ? '' : form.approverRole })}><option value="">Usar papel</option>{options?.users.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</NativeSelect></Field><Field label="Papel aprovador"><NativeSelect disabled={!!form.approverUserId} value={form.approverRole ?? ''} onChange={(e) => setForm({ ...form, approverRole: e.target.value })}><option value="">Selecione</option><option value="MANAGER">Gestor</option><option value="DIRECTOR">Diretoria</option><option value="COMPANY_ADMIN">Administrador</option></NativeSelect></Field></>}
    <DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={loading} onClick={() => onSubmit(cleanPayload(form))}>{loading ? 'Salvando...' : 'Salvar cadastro'}</Button></DialogFooter>
  </DialogContent></Dialog>;
}

export function ImportDialog({ open, warehouses, loading, onOpenChange, onSubmit }: CommonProps & { warehouses?: ProcurementOptions['warehouses']; onSubmit: Submit }) {
  const [file, setFile] = useState<File | null>(null); const [warehouseId, setWarehouseId] = useState('');
  useEffect(() => { if (open) { setFile(null); setWarehouseId(''); } }, [open]);
  async function submit() { if (!file) return; const base64 = await fileBase64(file); onSubmit({ xlsxBase64: base64, warehouseId: warehouseId || null, idempotencyKey: operationKey('catalog-import') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Importar catálogo e saldos iniciais</DialogTitle><DialogDescription>Colunas: codigo, nome, tipo, unidade, grupo, estoque_minimo, estoque_maximo, saldo_inicial e custo_unitario.</DialogDescription></DialogHeader><Field label="Arquivo XLSX"><Input type="file" accept=".xlsx" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></Field><Field label="Almoxarifado dos saldos iniciais"><NativeSelect value={warehouseId} onChange={(e) => setWarehouseId(e.target.value)}><option value="">Somente catálogo</option>{warehouses?.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</NativeSelect></Field><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={loading || !file} onClick={submit}>{loading ? 'Importando...' : 'Importar XLSX'}</Button></DialogFooter></DialogContent></Dialog>;
}

interface CommonProps { open: boolean; loading?: boolean; onOpenChange: (open: boolean) => void }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function WarehouseSelect({ value, options, onChange }: { value: string; options?: ProcurementOptions; onChange: (value: string) => void }) { return <NativeSelect value={value} onChange={(e) => onChange(e.target.value)}><option value="">Selecione</option>{options?.warehouses.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</NativeSelect>; }
function cleanPayload(value: any): any { if (Array.isArray(value)) return value.map(cleanPayload); if (!value || typeof value !== 'object') return value; return Object.fromEntries(Object.entries(value).map(([key, inner]) => [key, inner === '' ? null : cleanPayload(inner)])); }
function operationKey(prefix: string) { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`; }
function money(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value || 0); }
function fileBase64(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] ?? ''); reader.onerror = reject; reader.readAsDataURL(file); }); }
